-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

INSERT INTO public.categories (slug, name, description, sort_order) VALUES
('chatgpt', 'ChatGPT 专区', 'Plus / Pro 5X / Pro 20X 会员代充与账号权益', 1),
('claude', 'Claude 专区', 'Claude Pro / Max 订阅充值', 2),
('grok', 'Grok 专区', 'Grok Super / Premium 订阅', 3),
('gemini', 'Gemini 专区', 'Gemini Advanced / AI Pro / Ultra', 4),
('coding', 'AI 编程工具', 'Codex / Cursor / Copilot 等开发向订阅', 5),
('other', '其他权益', '流媒体、云服务与其他数字权益', 9)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (id, category_slug, badge, title, subtitle, price, original_price, cover_url, delivery_method, stock_level, sold_base, is_hot, sort_order, tips_title, tips_body, risk_title, risk_body, official_title, official_body, support_title, support_body) VALUES
('chatgpt-plus-month', 'chatgpt', '本周爆款', 'ChatGPT Plus 月卡', '官方 Plus 会员 · 30 天 · GPT-5 优先访问 + 更高额度', 138.00, 168.00, 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-chatgpt-plus.png?auth_key=aa7ba2b1e70afdbd786f7cae9a46cbcd6543153bd05a88082bfaf1aaea8a511d', 'auto', 'many', 2380, true, 1,
 '商品详情', '本商品为 ChatGPT Plus 一个月时长的会员权益交付。下单后系统自动发放兑换凭证，按详情页教程在自有账号内完成激活即可享受 Plus 全部能力：更高请求上限、优先响应、最新模型访问权限与高级功能内测资格。',
 '使用提醒', '请确认您的账号注册地区与网络环境可正常访问官方服务。凭证一经发出即视为已消耗，无法撤回或换绑他人账号；若激活过程中提示区域限制，请先更换合规网络环境后重试。',
 '风险说明', '本站提供的是正规渠道获取的兑换凭证，非共享账号、非破解服务。请勿将凭证转卖或在多个账号间反复尝试使用，异常调用可能导致凭证失效。因买家自身账号违规被封禁所产生的损失不在售后范围内。',
 '常见问题', '发货后多久能激活？通常 1 分钟内自动发卡，收到凭证后按教程操作 3 分钟即可完成。若长时间未收到，请使用查单页凭订单号重新获取。'),
('chatgpt-pro-5x', 'chatgpt', '高额度', 'ChatGPT Pro 5X', '面向重度使用者的加量档位 · 30 天 · 适合日常高频创作', 328.00, 398.00, 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-chatgpt-pro.png?auth_key=d6df75ceb0dc61a9a7f0148453cd84b82cf1405b6de6370f3101cdcd35cc9c64', 'auto', 'some', 640, false, 2,
 '商品详情', 'Pro 5X 档位提供高于 Plus 的请求配额与推理资源优先级，适合内容创作者、研究人员与需要长上下文连续工作的用户。有效期 30 天，到期不自动续费。',
 '使用提醒', '该档位为一次性权益交付，不支持中途降级或折算为 Plus 时长。建议根据实际用量选择档位，避免资源闲置。',
 '风险说明', '高额度权益受官方策略调整影响，具体可用模型与限额以账号内实际显示为准。如遇官方规则变更导致权益范围变化，本站将按比例补偿时长而非退款。',
 '常见问题', '能否与 Plus 叠加？同一账号同一时间仅存在一个生效档位，建议在当前周期结束前续购同档位以保持连续性。'),
('chatgpt-pro-20x', 'chatgpt', '顶配', 'ChatGPT Pro 20X', '极限额度 · 30 天 · 团队与专业生产力场景首选', 888.00, 1088.00, 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-chatgpt-pro.png?auth_key=d6df75ceb0dc61a9a7f0148453cd84b82cf1405b6de6370f3101cdcd35cc9c64', 'auto', 'few', 120, false, 3,
 '商品详情', '20X 为本站最高额度档位，适用于高强度批量生成、长文档处理与多轮复杂推理场景。交付方式与 5X 一致，凭证自动发放。',
 '使用提醒', '由于额度较高，请确保账号绑定信息完整且状态正常后再激活，避免因账号风控造成权益浪费。',
 '风险说明', '极端高频调用仍可能触发官方限流机制，此为平台侧行为，与凭证质量无关。建议合理分配调用节奏。',
 '常见问题', '支持开具凭证吗？如需对公采购或报销材料，请在下单备注中说明并联系客服处理。'),
('claude-pro', 'claude', '推荐', 'Claude Pro 月卡', 'Claude Pro 订阅 · 30 天 · Opus 访问权 + 扩展用量', 158.00, 188.00, 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-claude.png?auth_key=eaca9a266c0431adffaf1f7fb025560a209e14b8b577e1c212737f31183970d1', 'auto', 'many', 1560, true, 4,
 '商品详情', 'Claude Pro 提供高峰时段优先访问、更高消息上限以及对最强模型的完整使用权，尤其擅长长文本理解、代码编写与结构化写作。',
 '使用提醒', '激活前请确认账号已完成手机号验证，未完成验证的账号可能无法加载 Pro 权益。',
 '风险说明', 'Claude 对部分地区的注册与使用存在限制，请自行评估账号所在区域的可用性。因区域不可用导致的激活失败可申请换发凭证。',
 '常见问题', '有年付方案吗？本站按单个周期售卖，如需长期使用可分次购买，累计消费满额会自动发放老客折扣码。'),
('claude-max-5x', 'claude', '重度', 'Claude Max 5X', 'Max 档 · 30 天 · 高用量 Claude Code 与工作流', 880.00, 999.00, 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-claude.png?auth_key=eaca9a266c0431adffaf1f7fb025560a209e14b8b577e1c212737f31183970d1', 'auto', 'few', 88, false, 5,
 '商品详情', 'Max 5X 面向开发者与自动化工作流，提供数倍于 Pro 的周期间用量，配合 Claude Code 可在大型仓库中持续作业。',
 '使用提醒', 'Max 权益按滚动周期计算用量，建议避开周期末集中调用，以免提前耗尽当周额度。',
 '风险说明', '用量上限由官方动态调整，本站不承诺固定条数。若实际额度显著低于页面描述，可在有效期内提交截图申请差额补偿。',
 '常见问题', '适合个人使用吗？普通写作与研究场景 Pro 已足够，Max 更适合每日长时间编码的用户。'),
('grok-super', 'grok', '热门', 'Grok Super 月卡', 'Grok SuperGrok · 30 天 · 深度推理与图像生成', 128.00, 158.00, 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-grok.png?auth_key=488653ab265e4ceb7e1ff56712fa122051758a11ecd53f44c25a215b59ec2ce4', 'auto', 'many', 720, true, 6,
 '商品详情', 'Grok Super 解锁更快响应、更大上下文窗口与 Imagine 图像生成能力，实时信息检索是其突出优势。',
 '使用提醒', '需绑定支持该功能的账号类型，部分新注册账号可能存在功能灰度差异。',
 '风险说明', '实时检索类回答的准确性依赖数据源，请勿将其作为投资、医疗等专业决策的唯一依据。',
 '常见问题', '和 Plus 比怎么选？追热点与实时资讯选 Grok，长文与代码选 Claude，通用创作选 ChatGPT。'),
('gemini-pro', 'gemini', '生态', 'Gemini AI Pro', 'Google AI Pro · 30 天 · 超大上下文 + Workspace 联动', 118.00, 148.00, 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-gemini.png?auth_key=6e517498cd93d027af58686e40b539f0f73fc48be9b6f3e788655c1150bd5eb0', 'auto', 'many', 930, false, 7,
 '商品详情', 'Google AI Pro 除模型能力外还附带云端存储与全家桶协同，适合已在 Google 生态内办公的用户。',
 '使用提醒', '权益与 Google 账号强绑定，激活后请勿随意更换主账号，跨账号迁移不支持。',
 '风险说明', 'Google 对家庭组共享的规则较为严格，请勿用于违反条款的多人群组分发。',
 '常见问题', '包含存储吗？包含，具体容量以账号后台显示为准。'),
('codex-credits', 'coding', '开发者', 'Codex 用量包', 'AI 编程代理用量 · 适合 CI 与日常重构', 268.00, 328.00, 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-codex.png?auth_key=3b495332e5181469d5dcbcceaa6affdca856041de063fc52b471b04570f0c584', 'auto', 'some', 210, false, 8,
 '商品详情', '面向 Codex CLI 与云端代理的用量交付，覆盖代码补全、批量重构与测试生成等典型工程任务。',
 '使用提醒', '请在项目根目录配置好运行环境后再消耗额度，环境调试阶段的调用同样计入用量。',
 '风险说明', '涉及私有代码上传时，请自行确认企业合规要求；本站不接触也不存储任何买家代码。',
 '常见问题', '可以开发票吗？个人订单提供电子收据，企业采购请联系客服。'),
('cursor-pro', 'coding', '编辑器', 'Cursor Pro 月卡', 'AI 原生编辑器 Pro · 30 天 · 无限 Tab + 快速请求', 148.00, 178.00, 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-codex.png?auth_key=3b495332e5181469d5dcbcceaa6affdca856041de063fc52b471b04570f0c584', 'auto', 'some', 460, false, 9,
 '商品详情', 'Cursor Pro 解锁高级模型快速请求额度与后台 Agent 能力，是目前最流行的 AI 编程工作流之一。',
 '使用提醒', '权益跟随邮箱账号生效，下单时填写的接收邮箱请务必准确。',
 '风险说明', '官方对免费试用与付费账号的模型池划分较细，个别模型可用性可能随版本变动。',
 '常见问题', '支持 IDE 插件吗？Cursor 本身是独立编辑器，无需额外插件。')
ON CONFLICT (id) DO NOTHING;

