-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS close_reason TEXT;

COMMENT ON COLUMN public.orders.expires_at IS '支付时限截止时刻，建单时 = created_at + 30 分钟；NULL 表示本功能上线前的老订单，不限时';
COMMENT ON COLUMN public.orders.close_reason IS '关闭来源：timeout_auto 超时自动关闭 / admin_manual 管理员手动关闭；NULL 为历史遗留，UI 兜底显示管理员手动关闭';

CREATE INDEX IF NOT EXISTS orders_expire_pending_idx
  ON public.orders (expires_at)
  WHERE status IN ('pending_payment', 'pay_processing') AND expires_at IS NOT NULL;

