-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 消费返佣结算引擎：订单 completed 触发计佣 + 统计扩展 + 明细 RPC

-- 1) 计佣核心函数（由触发器调用，SECURITY DEFINER）
CREATE OR REPLACE FUNCTION public.process_order_commission(_order_id TEXT)
RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  o RECORD;
  buyer RECORD;
  cfg JSONB;
  g_enabled BOOLEAN;
  g_window INT;
  g_mode TEXT;
  g_value NUMERIC;
  g_cap NUMERIC;
  g_min NUMERIC;
  pc JSONB;
  c_enabled BOOLEAN;
  c_mode TEXT;
  c_value NUMERIC;
  c_cap NUMERIC;
  c_min NUMERIC;
  reward NUMERIC(10,2);
  got INT;
  coupon UUID;
BEGIN
  SELECT * INTO o FROM public.orders WHERE id = _order_id;
  IF NOT FOUND OR o.user_id IS NULL THEN RETURN; END IF;

  -- 买家必须已被邀请归因
  SELECT id, invited_by, created_at INTO buyer FROM public.profiles WHERE id = o.user_id;
  IF buyer.invited_by IS NULL THEN RETURN; END IF;

  -- 全局配置
  SELECT value INTO cfg FROM public.site_settings WHERE key = 'referral';
  cfg := coalesce(cfg, '{}'::jsonb);
  g_enabled := coalesce((cfg ->> 'commission_enabled')::BOOLEAN, true);
  g_window := coalesce((cfg ->> 'commission_window_days')::INT, 30);
  g_mode := coalesce(cfg ->> 'default_mode', 'rate');
  g_value := coalesce((cfg ->> 'default_value')::NUMERIC, 8);
  g_cap := coalesce((cfg ->> 'default_cap')::NUMERIC, 50);
  g_min := coalesce((cfg ->> 'min_amount')::NUMERIC, 30);
  IF NOT g_enabled THEN RETURN; END IF;

  -- 30 天窗口：以「支付完成时间」对比买家注册时间
  IF o.created_at < buyer.created_at - make_interval(days => 1) THEN
    -- 下单早于注册归因（异常数据），跳过
    RETURN;
  END IF;
  IF coalesce(o.updated_at, o.created_at) > buyer.created_at + make_interval(days => g_window) THEN
    RETURN;
  END IF;

  -- 商品级覆盖优先；未单独配置的商品默认不参与返佣（避免店主未知情被全局扣佣）
  SELECT commission INTO pc FROM public.products WHERE id = o.product_id;
  IF pc IS NULL OR (pc ->> 'enabled') IS DISTINCT FROM true THEN
    RETURN;
  END IF;
  c_mode := coalesce(pc ->> 'mode', g_mode);
  c_value := coalesce((pc ->> 'value')::NUMERIC, g_value);
  c_cap := coalesce((pc ->> 'cap')::NUMERIC, g_cap);
  c_min := coalesce((pc ->> 'min_amount')::NUMERIC, g_min);

  -- 计佣基数 = 实付金额；比例模式需达到门槛
  reward := CASE WHEN c_mode = 'fixed' THEN c_value
                 ELSE round(coalesce(o.amount, 0) * c_value / 100.0, 2) END;
  IF c_mode = 'rate' AND coalesce(o.amount, 0) < c_min THEN RETURN; END IF;
  reward := LEAST(reward, c_cap);
  IF reward <= 0 THEN RETURN; END IF;

  -- 给邀请人发券（受 max_reward_count 上限约束，达上限仍记录 capped）
  SELECT count(*) INTO got FROM public.referral_rewards WHERE inviter_id = buyer.invited_by;
  IF got < coalesce((cfg ->> 'max_reward_count')::INT, 20) THEN
    INSERT INTO public.referral_rewards (inviter_id, invitee_id, code, amount, min_amount)
    VALUES (buyer.invited_by, buyer.id,
            'CM' || upper(substr(md5(random()::TEXT || clock_timestamp()), 1, 10)),
            reward, greatest(c_min - reward, 0))
    RETURNING id INTO coupon;
    INSERT INTO public.commission_records (order_id, inviter_id, invitee_id, product_id, product_title, base_amount, reward_amount, coupon_id, status)
    VALUES (_order_id, buyer.invited_by, buyer.id, o.product_id,
            coalesce(o.product_snapshot ->> 'title', o.product_id), o.amount, reward, coupon, 'granted')
    ON CONFLICT (order_id) DO NOTHING;
  ELSE
    INSERT INTO public.commission_records (order_id, inviter_id, invitee_id, product_id, product_title, base_amount, reward_amount, coupon_id, status)
    VALUES (_order_id, buyer.invited_by, buyer.id, o.product_id,
            coalesce(o.product_snapshot ->> 'title', o.product_id), o.amount, reward, NULL, 'capped')
    ON CONFLICT (order_id) DO NOTHING;
  END IF;
EXCEPTION WHEN OTHERS THEN
  -- 计佣失败绝不能阻断发货主链路
  RAISE WARNING 'process_order_commission failed for order %: %', _order_id, SQLERRM;
END;
$$;

-- 2) 触发器：订单首次变 completed 时异步无关地同步计佣
CREATE OR REPLACE FUNCTION public.trg_fn_order_commission()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  PERFORM public.process_order_commission(NEW.id);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_order_commission ON public.orders;
CREATE TRIGGER trg_order_commission
  AFTER UPDATE OF status ON public.orders
  FOR EACH ROW
  WHEN (NEW.status = 'completed' AND OLD.status <> 'completed')
  EXECUTE FUNCTION public.trg_fn_order_commission();

-- 3) 统计扩展：新增累计返佣与记录数两列（返回类型变更需先 DROP）
DROP FUNCTION IF EXISTS public.my_referral_stats();
CREATE OR REPLACE FUNCTION public.my_referral_stats()
RETURNS TABLE (ok BOOLEAN, invite_count BIGINT, available_count BIGINT, available_amount NUMERIC, used_count BIGINT, total_commission NUMERIC, commission_count BIGINT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  uid UUID := auth.uid();
BEGIN
  IF uid IS NULL THEN
    RETURN QUERY SELECT false, 0, 0, 0::NUMERIC, 0, 0::NUMERIC, 0;
    RETURN;
  END IF;
  RETURN QUERY SELECT
    true,
    (SELECT count(*) FROM public.profiles WHERE invited_by = uid),
    (SELECT count(*) FROM public.referral_rewards WHERE inviter_id = uid AND status = 'available'),
    (SELECT coalesce(sum(amount), 0)::NUMERIC FROM public.referral_rewards WHERE inviter_id = uid AND status = 'available'),
    (SELECT count(*) FROM public.referral_rewards WHERE inviter_id = uid AND status = 'used'),
    (SELECT coalesce(sum(reward_amount), 0)::NUMERIC FROM public.commission_records WHERE inviter_id = uid AND status = 'granted'),
    (SELECT count(*) FROM public.commission_records WHERE inviter_id = uid);
END;
$$;
REVOKE ALL ON FUNCTION public.my_referral_stats() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.my_referral_stats() TO authenticated;

-- 4) 我的返佣明细（好友名脱敏：只暴露邮箱前缀首字符）
CREATE OR REPLACE FUNCTION public.my_commission_records()
RETURNS TABLE (ok BOOLEAN, id UUID, order_id TEXT, friend_name TEXT, product_title TEXT, base_amount NUMERIC, reward_amount NUMERIC, status TEXT, created_at TIMESTAMPTZ)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  uid UUID := auth.uid();
BEGIN
  IF uid IS NULL THEN
    RETURN QUERY SELECT false, NULL::UUID, NULL::TEXT, NULL::TEXT, NULL::TEXT, 0::NUMERIC, 0::NUMERIC, NULL::TEXT, NULL::TIMESTAMPTZ WHERE false;
    RETURN;
  END IF;
  RETURN QUERY
    SELECT a.ok, a.id, a.order_id, a.friend_name, a.product_title, a.base_amount, a.reward_amount, a.status, a.created_at
    FROM (
      SELECT true AS ok, cr.id, cr.order_id,
             coalesce(nullif(left(p.username, 1), ''), left(coalesce(p.email, '好'), 1)) || '**' AS friend_name,
             cr.product_title, cr.base_amount, cr.reward_amount, cr.status, cr.created_at
      FROM public.commission_records cr
      LEFT JOIN public.profiles p ON p.id = cr.invitee_id
      WHERE cr.inviter_id = uid
      ORDER BY cr.created_at DESC
      LIMIT 20
    ) AS a;
END;
$$;
REVOKE ALL ON FUNCTION public.my_commission_records() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.my_commission_records() TO authenticated;

