-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 按 bei-bei.shop 的商品结构与价格重构商品目录（UPSERT，保留历史订单外键）

INSERT INTO public.products (id, category_slug, badge, title, subtitle, price, original_price, cover_url, delivery_method, stock_level, sold_base, is_hot, sort_order, is_active, tips_title, tips_body, risk_title, risk_body, official_title, official_body, support_title, support_body) VALUES

('chatgpt-plus-month', 'chatgpt', '本周爆款', 'ChatGPT Plus 月卡 ｜ iOS 充值', '充值到自己账号 · 自助卡密 · 兑换即订阅一个月 Plus', 132.00, 158.00,
 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-chatgpt-plus-1.png?auth_key=ddd328996b7704cdef1b2a436211fd5b72cf13cc6167b4e361fc286c236e219c',
 'auto', 'few', 6423, true, 1, true,
 '商品详情', 'iOS 土区官方正规充值｜GPT Plus 1 个月。本商品为 GPT Plus 自助充值卡密，24 小时自动充值，预计 1-3 分钟充值成功。兑换成功后可获得 1 个月 ChatGPT Plus 订阅（官方价 20 美元），保证正规充值。页面说明的 iOS 端充值指的是充值方式，你只需要有 GPT 账号即可充值。',
 '使用提醒', '原 Plus 未到期会被覆盖，不叠加时长。小众邮箱容易掉订阅，请勿使用微软邮箱，建议使用谷歌邮箱。如果原账号订阅的是 GPT Pro，Plus 卡密无法覆盖订阅，请更换新号或等待 Pro 到期后再充值。此渠道不缺凭证、不超卖，秒冲。',
 '风险说明', '不建议囤货，也不接受囤货多天后再反馈无法使用并要求退款。由于官方风控或渠道规则变化，兑换方式可能随时失效，请务必即买即用；如当天无法使用，请当天联系反馈处理。下单前必读：1. 需已有 GPT 账号；2. 账号需为个人版，若加入过 Team 空间请先切回个人版；3. 卡密售出后除无法兑换外不退不换；4. 卡密请当天购买、当天使用。',
 '常见问题', '兑换失败：继续重试，或等待 30 分钟后再试。充值成功但未显示 Plus：退出账号后重新登录 GPT。网页版看不到 Plus 模型：使用浏览器无痕模式重新登录。Codex 额度未刷新：属于官方延迟，等待 30 分钟后重新登录 Codex 随意提问一次即可激活。'),

('chatgpt-plus-ph', 'chatgpt', '菲区卡充', 'ChatGPT Plus 月卡 ｜ 菲区卡充', '充值到自己账号 · 秒冲 · 卡密可囤五天', 115.00, 138.00,
 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-chatgpt-plus-1.png?auth_key=ddd328996b7704cdef1b2a436211fd5b72cf13cc6167b4e361fc286c236e219c',
 'auto', 'many', 7142, true, 2, true,
 '商品详情', '菲律宾卡付官方正规充值｜本商品为 GPT Plus 自助充值卡密，兑换成功后可获得一个月 ChatGPT Plus 订阅（官方价 20 美元）。24 小时自动充值，预计 1-3 分钟充值成功，保证正规充值。',
 '使用提醒', '不支持覆盖，不支持覆盖，不支持覆盖。账号必须没有订阅状态／免费版才可以充值。小众邮箱容易掉订阅，建议使用谷歌邮箱；不建议使用微软邮箱，很容易风控。如果原账号订阅的是 GPT Pro，Plus 卡密无法覆盖订阅，请更换新号或等待 Pro 订阅到期后再充值。',
 '风险说明', '不建议囤货，也不接受囤货多天后再反馈无法使用并要求退款（不支持退款）。由于官方风控或渠道规则变化，兑换方式可能随时失效，请务必即买即用。下单前必读：1. 需已有 GPT 账号；2. 账号需为个人版，加入过 Team 空间请先切回个人版再获取 Token；3. 接受不退不换，卡密售出后除非无法兑换否则不退不换；4. 卡密请当天购买、当天使用。拍下即默认已阅读并接受以上条款，介意勿拍。',
 '常见问题', '兑换失败：继续重试，或等待 30 分钟后再试。充值成功但未显示 Plus：退出账号后重新登录 GPT。网页版看不到 Plus 模型：使用浏览器无痕模式重新登录。Codex 额度未刷新：属于官方延迟，等待 30 分钟后重新登录 Codex 随意提问一次即可激活。'),

('chatgpt-pro-5x', 'chatgpt', '高额度', 'ChatGPT Pro 5X ｜ 1 个月 ｜ iOS 充值', '【5X-100刀款】充值自己账号 · 秒冲 · 质保30天', 650.00, 720.00,
 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-chatgpt-pro5x.png?auth_key=2d956cbd28235b940e1cb9d6d573f8462ef103118bcedda8ff05691bc25091f8',
 'auto', 'few', 1040, false, 3, true,
 '商品详情', 'iOS 官方正规充值｜GPT Pro 5x 1 个月。本商品为 GPT Pro 5x 自助充值卡密，24 小时自动充值，预计 1-3 分钟充值成功。兑换成功后可获得 1 个月 GPT Pro 5x 订阅（官方价 100 美元）。若你的 Plus 是 iOS 端充值的，可以覆盖上去。',
 '使用提醒', '覆盖说明：此商品支持覆盖账号已有的订阅套餐。例如当前是 Plus，覆盖成功后订阅时间从覆盖当天重新计算，有效期 1 个月；套餐覆盖不会重置原有额度，只补充对应额度差额（Plus 升 Pro 5X 补 4X 额度）。同类型套餐覆盖只更新有效期、不恢复额度。原 Plus 未到期会被覆盖，不叠加时长；请勿使用微软邮箱，建议使用谷歌邮箱。不要拿之前在别处用低价卡密充值过的号来充值，容易封号。',
 '风险说明', '质保规则：质保 30 天不掉订阅，不质保封号情况。30 天内出现掉订阅可按剩余天数退差价。封号问题 99% 为用户自身使用环境或账号本身风控导致，不在售后范围内；请使用干净稳定的 IP 环境，不要多人共享或频繁切换地区登录。不建议囤货，兑换方式可能因官方风控随时失效，务必即买即用。',
 '常见问题', '兑换失败：继续重试，或等待 30 分钟后再试。充值成功但未显示订阅：退出账号后重新登录 GPT。网页版未显示：使用浏览器无痕模式重新登录。Codex 额度未刷新：属于官方延迟，等待 30 分钟后重新登录 Codex 随意提问一次即可激活。'),

('chatgpt-pro-5x-card', 'chatgpt', '人工处理', 'ChatGPT Pro 5X 月卡 ｜ 官方卡充', '【5X-100刀款】自助卡密 · 质保订阅 · 卡密可囤五天', 670.00, 750.00,
 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-chatgpt-pro5x.png?auth_key=2d956cbd28235b940e1cb9d6d573f8462ef103118bcedda8ff05691bc25091f8',
 'auto', 'many', 372, false, 4, true,
 '商品详情', '提交订单后将由人工处理，正常处理时间约 1-30 分钟，24 小时接单。账单请自行保存。本服务仅用于 GPT Plus / GPT Pro 正价订阅消费，使用本服务完成的所有正价订阅消费原则上不支持退款；除非因平台或本服务本身原因导致无法完成服务，才可按售后规则处理。',
 '使用提醒', '禁止提交说明：目前账号如果已是 Plus / Team / Pro 资格账号，请勿提交充值订单。此前购买或使用过以下类型账号/订阅的也请勿提交：非正常 Pro/Plus、0 元购 Pro/Plus、谷歌内购订阅、低价黑冲账号、存在异常订阅记录的账号。否则可能导致订阅掉线、触发邮件欺诈风控、充值失败、账号异常，请更换正常账号后再提交订单。',
 '风险说明', '违规行为（邮件欺诈、网络滥用、违反平台条款、异常环境账号）导致的充值失败不支持退款。账号封禁、KYC 未通过、需绑定手机号、自行取消订阅等问题需客户自行处理，本店不承担责任且不予退款。如出现订阅掉线需客户自行联系 OpenAI 官方客服；如官方最终完成退款，本店在收到退款后扣除 20% 处理费用退还剩余款项。',
 '常见问题', '建议使用 Gmail（强烈建议）、163、126、QQ 邮箱提交订单。充值成功后系统会向您提供的邮箱发送通知。请提供需要充值的 GPT Plus / Pro 套餐账号；如账号未购买套餐，需按要求提交账号 Token 或 Cookie（TXT 文本格式）。提交订单即代表您已理解并接受本商品全部须知与协议内容。'),

('chatgpt-pro-20x', 'chatgpt', '推理强', 'ChatGPT Pro 200刀月卡 ｜ 卡充秒充', '【10X-200刀款】充值自己账号 · 质保订阅 · 卡密可囤三天', 1050.00, 1180.00,
 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-chatgpt-pro20x.png?auth_key=19f0fc529fe7a51afc4b409c9813de5f49ce6a35eda6f9ddd0c1d9245d0e7bfa',
 'auto', 'many', 1421, true, 5, true,
 '商品详情', '提交订单后由系统自动处理，正常处理时间约 1-30 分钟。如果你是订阅到期后重新订阅的，仍是 20X 的额度。账单请自行保存。本服务仅用于 GPT Plus / GPT Pro 正价订阅消费，正价订阅消费原则上不支持退款。',
 '使用提醒', '禁止提交说明：目前账号如果已是 Plus / Team / Pro 资格账号，请勿提交充值订单。此前使用过非正常 Pro/Plus、0 元购、谷歌内购订阅、低价黑冲账号、存在异常订阅记录账号的也请勿提交，否则可能导致订阅掉线、触发风控、充值失败、账号异常。请勿使用微软邮箱。',
 '风险说明', '违规行为导致的充值失败、订阅异常、账号限制均不支持退款。账号封禁、KYC 验证未通过、需绑定手机号、客户自行取消订阅等需客户自行处理，不予退款。订阅掉线需客户自行联系 OpenAI 官方客服处理，退款与否以官方判断为准；如官方退款，本店收到后扣除 20% 处理费退还剩余款项。',
 '常见问题', '建议使用 Gmail（强烈建议）、163、126、QQ 邮箱。充值成功后向邮箱发送通知。需提供待充值的 GPT 套餐账号；账号未购买套餐时需按要求提交 Token 或 Cookie（TXT 格式）。提交订单即代表接受本商品全部须知与协议。'),

('chatgpt-pro-20x-renew', 'chatgpt', '续费专用', 'ChatGPT Pro 20X 月卡 ｜ 菲区续费卡密', '【20X-200刀款】只限菲区卡充 20x 续费用户', 1090.00, 1200.00,
 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-chatgpt-pro20x.png?auth_key=19f0fc529fe7a51afc4b409c9813de5f49ce6a35eda6f9ddd0c1d9245d0e7bfa',
 'auto', 'some', 9, false, 6, true,
 '商品详情', '提交订单后自动处理，正常处理时间约 1-30 分钟。只限菲区卡充 20x 续费：必须是 Pro 状态才可以续费，free 状态请拍其他商品。建议提前 1-2 天购买然后续费即可。账单请自行保存。',
 '使用提醒', '禁止提交说明：账号已是 Plus / Team / Pro 之外资格状态的请勿误拍；此前使用过非正常 Pro/Plus、0 元购、谷歌内购订阅、低价黑冲、异常订阅记录账号的请勿提交，否则可能订阅掉线、触发风控、充值失败。请勿使用微软邮箱。',
 '风险说明', '本服务仅用于正价订阅消费，正价订阅消费原则上不支持退款。违规行为、账号封禁、KYC、绑定手机号、自行取消订阅等问题需客户自行处理，不予退款。如官方完成退款，本店收到后扣除 20% 处理费退还剩余款项。',
 '常见问题', '建议使用 Gmail（强烈建议）、163、126、QQ 邮箱。充值成功后邮箱通知。需提供待续费账号；未购买套餐的账号需按要求提交 Token 或 Cookie（TXT 格式）。提交订单即代表接受全部须知与协议。'),

('chatgpt-pro-20x-account', 'chatgpt', '成品号', 'ChatGPT Pro 200刀 月卡 ｜ 成品号', 'Pro 20X 成品号 · 1 个月订阅 · 质保订阅', 1200.00, 1350.00,
 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-chatgpt-pro20x.png?auth_key=19f0fc529fe7a51afc4b409c9813de5f49ce6a35eda6f9ddd0c1d9245d0e7bfa',
 'auto', 'few', 18, false, 7, true,
 '商品详情', '本商品为 ChatGPT Pro 20X 成品号，保证正规官方充值，订阅有效期 1 个月。交付说明：下单后请联系客服安排制作，需人工处理，预计 10 分钟至 2 小时完成交付。',
 '使用提醒', '成品号为独立新账号交付，不适用覆盖类商品规则。请妥善保管交付的账号信息，不要多人共享或频繁切换地区登录，避免触发平台风控。',
 '风险说明', '提供 30 天订阅质保，仅保障订阅，封号不在质保范围内。封号多数与账号本身状态或使用环境有关，请合理使用账号。',
 '常见问题', '账号交付问题：请联系客服协助处理。登录后未显示 Pro 订阅：退出账号后重新登录 GPT。网页版未显示：使用浏览器无痕模式重新登录。Codex 额度未刷新：属于官方延迟，等待 30 分钟后重新登录 Codex 随意提问一次即可激活。'),

('claude-pro', 'claude', '即将售罄', 'Claude Pro 月卡 ｜ iOS 充值', '充值到自己账号 · 秒冲 · 质保30天', 144.00, 168.00,
 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-claude-pro.png?auth_key=62cce8d734fc78bdf02adfa0b40b58654a3873e02106d1b68768d376066a4b56',
 'auto', 'few', 991, true, 8, true,
 '商品详情', 'Claude iOS 自助充值说明：24 小时自动充值，预计 1-3 分钟充值成功。本商品为 Claude iOS 正规充值，无需上号、无需提供账号密码，支持两种充值方式：1. SK 充值（推荐），充值时自动查询账户状态确认无异常再充值；2. Claude UID 自助充值，提供 Claude UID 即可完成，全程无需提供账号密码。只要持有卡密，24 小时均可自助充值；需等当前会员到期后才可续费。',
 '使用提醒', '不支持覆盖，不支持覆盖，不支持覆盖。账号处于逾期状态时禁止充值，否则可能导致不到账，后果自负。不懂 Claude 风控规则或小白请不要拍，容易封号。无论使用哪种充值方式，充值成功后出现封号均不在质保范围内，介意请勿拍。',
 '风险说明', '质保规则：质保 30 天不掉订阅，不质保封号情况。30 天内出现掉订阅可按剩余天数退差价。封号问题 99% 为用户自身使用环境或账号本身风控导致（频繁切换 IP、账号环境异常、账号本身存在风控），不在售后范围内。不管是被封还是逾期问题导致充值不到账，没有退款。拍下默认接受。',
 '常见问题', '充值失败：请等待一段时间后重新提交；多次提交仍失败请联系在线客服处理。下单前请确认会员到期后再进行续费。请使用干净稳定的 IP 环境，不要多人共享或频繁切换地区登录。'),

('grok-super', 'grok', '热门', 'Grok Super 月卡 ｜ iOS 充值', '充值到自己账号 · 印度区 iOS 正规 CDK · 质保订阅', 180.00, 198.00,
 'https://g.cdn.meoo.host/s5lynl8068w5/ai-images/cover-grok-super.png?auth_key=9b6f8101aa7e2932ce089d7b3029b97b02e8619a4acc79274032f355f03a336a',
 'auto', 'few', 371, true, 9, true,
 '商品详情', '本商品为印度区 iOS Grok Super 1 月充值 CDK。正规 iOS 印区充值，非零元购；支持安卓端 / iOS 端使用。CDK 未使用前长期有效，无固定到期时间；只要持有卡密，24 小时均可自助充值。',
 '使用提醒', '不支持覆盖，请保证你的账号没有订阅再充值。常见封号原因包括：批量注册账号、账号共享、频繁更换 IP、使用环境异常、询问敏感问题、翻译敏感话术等，请自行注意账号环境和使用方式，避免触发平台风控。',
 '风险说明', '本商品提供全程订阅质保。质保期内如掉订阅，按剩余天数退差价。封号多数情况下与账号本身状态或使用环境有关，封号不在售后范围内。',
 '常见问题', '充值入口与图文教程请以订单页发货内容为准，新手建议先看教程再操作。如遇充值失败请稍后重试，多次失败请联系客服并附上订单号。')

ON CONFLICT (id) DO UPDATE SET
  category_slug = EXCLUDED.category_slug,
  badge = EXCLUDED.badge,
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  cover_url = EXCLUDED.cover_url,
  stock_level = EXCLUDED.stock_level,
  sold_base = EXCLUDED.sold_base,
  is_hot = EXCLUDED.is_hot,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active,
  tips_title = EXCLUDED.tips_title,
  tips_body = EXCLUDED.tips_body,
  risk_title = EXCLUDED.risk_title,
  risk_body = EXCLUDED.risk_body,
  official_title = EXCLUDED.official_title,
  official_body = EXCLUDED.official_body,
  support_title = EXCLUDED.support_title,
  support_body = EXCLUDED.support_body,
  updated_at = NOW();

-- 暂时下架 bei-bei 未覆盖到的旧商品（保留数据，不影响历史订单）
UPDATE public.products SET is_active = false, updated_at = NOW()
 WHERE id IN ('claude-max-5x', 'gemini-pro', 'codex-credits', 'cursor-pro');

