-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 修复 order_close：原 RETURNS TABLE(ok, message) 在 PostgREST 下布尔列序列化不可靠，
-- 导致前端拿到异常结构被判失败（点「确认关闭」无反应）。
-- 改为标量 TEXT 返回（'OK' / 错误文案），与已验证可靠的 order_create_rpc 风格一致。
DROP FUNCTION IF EXISTS public.order_close(TEXT);

CREATE OR REPLACE FUNCTION public.order_close(_order_id TEXT)
RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  o RECORD;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RETURN '无权限执行该操作';
  END IF;
  SELECT * INTO o FROM public.orders WHERE id = _order_id;
  IF NOT FOUND THEN RETURN '订单不存在'; END IF;
  IF o.status = 'closed' THEN RETURN NULL; END IF; -- 幂等：已关闭视为成功
  UPDATE public.orders SET status = 'closed',
    timeline = timeline || jsonb_build_object('at', now(), 'label', '订单已关闭'), updated_at = NOW()
    WHERE id = _order_id;
  RETURN NULL; -- NULL = 成功
EXCEPTION WHEN OTHERS THEN
  RETURN '关闭失败：' || SQLERRM;
END;
$$;

REVOKE ALL ON FUNCTION public.order_close(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.order_close(TEXT) TO authenticated;

