-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 消费返佣：商品级配置列 + 返佣记录表 + RLS
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS commission JSONB;

CREATE TABLE IF NOT EXISTS public.commission_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id TEXT UNIQUE NOT NULL REFERENCES public.orders(id) ON DELETE SET NULL,
  inviter_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  invitee_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  product_id TEXT,
  product_title TEXT,
  base_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  reward_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  coupon_id UUID REFERENCES public.referral_rewards(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'granted',  -- granted | capped
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS commission_records_inviter_idx ON public.commission_records (inviter_id, created_at DESC);

ALTER TABLE public.commission_records ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS users_select_own_commission_records ON public.commission_records;
CREATE POLICY users_select_own_commission_records ON public.commission_records
  FOR SELECT USING (inviter_id = auth.uid());

