-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

INSERT INTO public.faqs (group_name, question, answer, sort_order) VALUES
('下单与支付', '支持哪些付款方式？', '目前支持支付宝转账与 USDT（TRC20）两种收款方式。下单页会展示对应收款信息，完成付款后回填转账凭证即可，店主确认到账后系统自动发货。', 1),
('下单与支付', '为什么没有在线自动扣款？', '虚拟商品跨境代充涉及渠道合规问题，本站采用「先下单锁定库存 → 人工核账 → 自动发卡」的流程，既保证资金安全也能避免异常订单误扣款。', 2),
('下单与支付', '付款后多久能收到卡密？', '正常营业时间内通常 5–15 分钟完成核账并自动发放；夜间提交的订单会在次日集中处理，处理完成后查单页状态会同步更新。', 3),
('发货与激活', '如何查询我的订单和卡密？', '进入「订单查询」页，输入下单时填写的订单号、邮箱或手机号以及自设的查询密码即可查看完整发货信息。请妥善保存这三项，连续输错 5 次会临时锁定 10 分钟。', 4),
('发货与激活', '卡密激活失败怎么办？', '请先按详情页教程逐步核对：账号地区、网络环境、是否已完成手机号验证。若确认操作无误仍失败，携带订单号与失败截图联系客服，可换发新凭证。', 5),
('发货与激活', '一个凭证能在多个账号上使用吗？', '不能。每个凭证仅可绑定一个账号，激活后即作废。请勿在公开场合泄露凭证内容。', 6),
('售后与退款', '哪些情况可以退款？', '凭证未使用且因渠道原因无法激活的，可申请全额退款或换发；已激活成功的权益不支持退款。因买家自身账号违规被封禁不属于可退范围。', 7),
('售后与退款', '退款多久到账？', '确认符合退款条件后，原路退回一般在 1–3 个工作日内完成；USDT 订单按提交时的汇率折算退回。', 8),
('账号与安全', '必须注册才能购买吗？', '不强制。游客可完整下单，凭「订单号 + 联系方式 + 查询密码」取货。注册后可在个人中心查看历史订单、享受会员折扣与老客专属码。', 9),
('账号与安全', '你们会拿到我的账号密码吗？', '不会。本站只交付兑换凭证，全程不需要也不应索取您的任何登录密码。任何索要密码的行为都不是本站客服。', 10)
ON CONFLICT DO NOTHING;

INSERT INTO public.coupons (code, type, value, min_amount, max_uses, per_user_limit, expires_at) VALUES
('ZHIHE10', 'fixed', 10.00, 100.00, 500, 1, '2026-12-31T23:59:59+08:00'),
('NEW20', 'fixed', 20.00, 300.00, 200, 1, '2026-12-31T23:59:59+08:00'),
('VIP5', 'percent', 5.00, 0.00, 1000, 99, '2026-12-31T23:59:59+08:00')
ON CONFLICT (code) DO NOTHING;

INSERT INTO public.site_settings (key, value) VALUES
('brand', '{"name":"智核","slogan":"AI 会员自助充值商城","subtitle":"海外 AI 订阅 · 正规渠道 · 自动发卡","logoText":"智核"}'::jsonb),
('contact', '{"wechat":"zhihe-service","qq":"88001234","email":"support@zhihe.shop","workTime":"每日 09:00 - 24:00","notice":"本店为虚拟商品自助商城，付款后请保留订单号与查询密码，这是唯一取货凭证。"}'::jsonb),
('payment', '{"alipay":{"account":"zhihe999@outlook.com","name":"智核数字服务","note":"转账请备注订单号后 6 位"},"usdt":{"network":"TRC20","address":"XU6YcNKqAqxGZrLbs0P5bHh8svtkaeGGit","note":"仅支持 TRON（TRC20）链转账，其他链转入无法找回；转账前请反复核对地址。"},"wechat":{"qr_url":"","account_name":"智核数字服务","note":"请添加店主微信后转账，务必备注订单号后 6 位；确认到账后立即发放卡密。"}}'::jsonb),
('seo', '{"title":"智核 · AI 会员自助充值商城","description":"ChatGPT Plus / Pro、Claude Pro / Max、Grok Super、Gemini AI Pro 等海外 AI 订阅正规渠道代充，自动发卡、订单可查、售后有保障。","keywords":"ChatGPT Plus 代充,Claude Pro 购买,AI 会员充值,Grok Super,Gemini Pro"}'::jsonb),
('announcement', '{"enabled":true,"title":"智核","subtitle":"请认准官方网址，谨防假冒。","official_url":"nl8068w5.meoo.info","security_note":"客服只通过首页展示的联系方式处理，谨防被骗。","warning_note":"下单前请看清商品介绍，有问题请先联系客服。","links":[{"label":"微信客服","url":"","icon":"chat"},{"label":"QQ 通知交流群","url":"","icon":"qq"},{"label":"Telegram 频道","url":"","icon":"telegram"}],"cta_label":"好的，我知道了","snooze_label":"24 小时内不再提醒","snooze_hours":24}'::jsonb),
('branding', '{"logo_url":"","name":"智核","tagline":"AI 会员自助充值"}'::jsonb)
ON CONFLICT (key) DO NOTHING;

