-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- ============================================
-- 频控白名单管理函数（SECURITY DEFINER，内部校验 admin）
-- 返回值范式沿用本项目：标量 TEXT，NULL = 成功，非 NULL = 错误文案
-- 归一化复用 public.normalize_contact(TEXT, TEXT)（黑名单迁移已建）
-- ============================================

CREATE OR REPLACE FUNCTION public.rate_limit_whitelist_add(
  _contact_type TEXT,
  _contact_value TEXT,
  _note TEXT DEFAULT '店主测试账号'
)
RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_norm TEXT;
  v_id UUID;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RETURN '无权限执行此操作';
  END IF;
  IF _contact_type NOT IN ('email', 'phone') THEN
    RETURN '联系方式类型不合法';
  END IF;
  v_norm := public.normalize_contact(_contact_type, _contact_value);
  IF v_norm = '' THEN
    RETURN '请填写要加入白名单的邮箱或手机号';
  END IF;

  -- 已有生效记录 → 视为重复
  SELECT id INTO v_id FROM rate_limit_whitelist
   WHERE contact_type = _contact_type AND contact_value = v_norm AND is_active
   LIMIT 1;
  IF v_id IS NOT NULL THEN
    RETURN '该联系方式已在白名单中';
  END IF;

  -- 有已移除的历史记录 → 重新置为生效
  UPDATE rate_limit_whitelist
     SET is_active = true,
         note = coalesce(nullif(btrim(_note), ''), '店主测试账号'),
         raw_value = btrim(_contact_value), created_by = auth.uid(), updated_at = now()
   WHERE contact_type = _contact_type AND contact_value = v_norm
     AND id = (SELECT id FROM rate_limit_whitelist
                WHERE contact_type = _contact_type AND contact_value = v_norm AND NOT is_active
                ORDER BY updated_at DESC LIMIT 1);
  IF FOUND THEN
    RETURN NULL;
  END IF;

  INSERT INTO rate_limit_whitelist (contact_type, contact_value, raw_value, note, created_by)
  VALUES (_contact_type, v_norm, btrim(_contact_value),
          coalesce(nullif(btrim(_note), ''), '店主测试账号'), auth.uid());
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.rate_limit_whitelist_remove(_id UUID)
RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_rows INT;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RETURN '无权限执行此操作';
  END IF;
  UPDATE rate_limit_whitelist
     SET is_active = false, updated_at = now()
   WHERE id = _id AND is_active;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  IF v_rows = 0 THEN
    RETURN '该记录已移除或不存在，请刷新后重试';
  END IF;
  RETURN NULL;
END;
$$;

REVOKE ALL ON FUNCTION public.rate_limit_whitelist_add(TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.rate_limit_whitelist_remove(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rate_limit_whitelist_add(TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.rate_limit_whitelist_remove(UUID) TO authenticated;

