-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 修复游客下单"提交失败"：
-- 根因：前端 insert().select('id') 附带 RETURNING，SELECT RLS 仅允许 user_id = auth.uid()，
-- 游客订单 user_id 为 NULL → RETURNING 读不回任何行 → Supabase 判定请求失败并回滚整条插入。
-- 方案：INSERT 策略保持原样；新增 anon_select_orders 策略放开「游客凭查询密码归属」这一支，
-- 使带 lookup_password_hash 的匿名订单可被创建者回读（卡密仍需 order_verify_lookup 三要素校验才展示）。

CREATE POLICY anon_select_orders ON public.orders
  FOR SELECT
  USING (user_id IS NULL AND lookup_password_hash IS NOT NULL);
