-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


UPDATE public.contents SET body = replace(body, E'\\n', E'\n') WHERE position(E'\\n' in body) > 0;

