-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 邀请有礼核心 RPC：取/建我的邀请码、注册归因并发奖、我的邀请统计

-- 1) 取当前用户邀请码（不存在则生成一个不易混淆的大写字母数字码）
CREATE OR REPLACE FUNCTION public.my_invite_code()
RETURNS TABLE (ok BOOLEAN, code TEXT, message TEXT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  uid UUID := auth.uid();
  c TEXT;
  i INT;
BEGIN
  IF uid IS NULL THEN
    RETURN QUERY SELECT false, NULL::TEXT, '请先登录';
    RETURN;
  END IF;
  SELECT invite_code INTO c FROM public.profiles WHERE id = uid;
  IF c IS NOT NULL THEN
    RETURN QUERY SELECT true, c, NULL::TEXT;
    RETURN;
  END IF;
  FOR i IN 1..12 LOOP
    -- 去掉易混字符 0O1I，避免口头传播出错
    c := upper(substr(md5(random()::TEXT || clock_timestamp()::TEXT || i), 1, 8));
    c := replace(replace(replace(replace(c, '0', 'X'), 'O', 'Y'), '1', 'Z'), 'I', 'W');
    IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE invite_code = c) THEN
      UPDATE public.profiles SET invite_code = c WHERE id = uid;
      RETURN QUERY SELECT true, c, NULL::TEXT;
      RETURN;
    END IF;
  END LOOP;
  RETURN QUERY SELECT false, NULL::TEXT, '邀请码生成失败，请稍后重试';
END;
$$;

-- 2) 注册归因：把被邀请人挂到邀请人名下，并给双方各发一张奖励券。
--    仅允许对「自己这条 profiles 且尚未被归因」的行执行，杜绝刷奖与重复发券。
CREATE OR REPLACE FUNCTION public.referral_bind(_invite_code TEXT)
RETURNS TABLE (ok BOOLEAN, reward_amount NUMERIC, message TEXT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  uid UUID := auth.uid();
  cfg JSONB;
  enabled BOOLEAN;
  amt NUMERIC;
  min_amt NUMERIC;
  max_cnt INT;
  inviter UUID;
  got INT;
BEGIN
  IF uid IS NULL THEN
    RETURN QUERY SELECT false, 0, '请先登录';
    RETURN;
  END IF;
  IF _invite_code IS NULL OR btrim(_invite_code) = '' THEN
    RETURN QUERY SELECT false, 0, '请填写邀请码';
    RETURN;
  END IF;

  SELECT value INTO cfg FROM public.site_settings WHERE key = 'referral';
  cfg := coalesce(cfg, '{}'::jsonb);
  enabled := coalesce((cfg ->> 'enabled')::BOOLEAN, true);
  amt := coalesce((cfg ->> 'reward_amount')::NUMERIC, 5);
  min_amt := coalesce((cfg ->> 'min_amount')::NUMERIC, 30);
  max_cnt := coalesce((cfg ->> 'max_reward_count')::INT, 20);
  IF NOT enabled THEN
    RETURN QUERY SELECT false, 0, '邀请活动暂未开启';
    RETURN;
  END IF;

  SELECT id INTO inviter FROM public.profiles
    WHERE upper(invite_code) = upper(btrim(_invite_code)) AND id <> uid;
  IF NOT FOUND THEN
    RETURN QUERY SELECT false, 0, '邀请码不存在或不可用';
    RETURN;
  END IF;

  -- 已归过因的账号不再重复绑定
  IF (SELECT invited_by FROM public.profiles WHERE id = uid) IS NOT NULL THEN
    RETURN QUERY SELECT false, 0, '该账号已绑定过邀请人';
    RETURN;
  END IF;
  -- 老账号（注册已久）不允许事后补绑，防套利
  IF (SELECT created_at FROM public.profiles WHERE id = uid) < NOW() - INTERVAL '1 day' THEN
    RETURN QUERY SELECT false, 0, '仅新注册账号可填写邀请码';
    RETURN;
  END IF;

  UPDATE public.profiles SET invited_by = inviter WHERE id = uid;

  SELECT count(*) INTO got FROM public.referral_rewards WHERE inviter_id = uid;
  IF got < max_cnt THEN
    INSERT INTO public.referral_rewards (inviter_id, invitee_id, code, amount, min_amount)
    VALUES (uid, inviter, 'RF' || upper(substr(md5(random()::TEXT || clock_timestamp()), 1, 10)), amt, min_amt);
  END IF;

  SELECT count(*) INTO got FROM public.referral_rewards WHERE inviter_id = inviter;
  IF got < max_cnt THEN
    INSERT INTO public.referral_rewards (inviter_id, invitee_id, code, amount, min_amount)
    VALUES (inviter, uid, 'RF' || upper(substr(md5(clock_timestamp()::TEXT || random()), 1, 10)), amt, min_amt);
  END IF;

  RETURN QUERY SELECT true, amt, '邀请关系已生效，奖励券已发放到你的账户';
END;
$$;

-- 3) 我的邀请概览：邀请人数 + 可用券余额（个人中心展示用，RLS 只放行自己的行）
CREATE OR REPLACE FUNCTION public.my_referral_stats()
RETURNS TABLE (ok BOOLEAN, invite_count BIGINT, available_count BIGINT, available_amount NUMERIC, used_count BIGINT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  uid UUID := auth.uid();
BEGIN
  IF uid IS NULL THEN
    RETURN QUERY SELECT false, 0, 0, 0::NUMERIC, 0;
    RETURN;
  END IF;
  RETURN QUERY SELECT
    true,
    (SELECT count(*) FROM public.profiles WHERE invited_by = uid),
    (SELECT count(*) FROM public.referral_rewards WHERE inviter_id = uid AND status = 'available'),
    (SELECT coalesce(sum(amount), 0)::NUMERIC FROM public.referral_rewards WHERE inviter_id = uid AND status = 'available'),
    (SELECT count(*) FROM public.referral_rewards WHERE inviter_id = uid AND status = 'used');
END;
$$;

REVOKE ALL ON FUNCTION public.my_invite_code() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.referral_bind(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.my_referral_stats() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.my_invite_code() TO authenticated;
GRANT EXECUTE ON FUNCTION public.referral_bind(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.my_referral_stats() TO authenticated;

