-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- ============================================
-- 自动加白第二步：把达标检查挂进共用发卡事务 order_assign_card
--   三条真实收款路径（支付宝到账 order_mark_paid、后台确认收款 order_confirm_payment、
--   站内余额支付 order_pay_with_balance）最终都走本函数 → 只在这里调用一次即全覆盖。
--   ⚠️ 后台「手动补发卡密」order_manual_deliver 不经过本函数——没有真实付款，不计入成交。
--   签名与返回 TABLE(ok, message) 完全不变 → 无需 DROP 重载。
--   参照原实现 migrations/20260920_081611_pay_autodelivery.sql:10-51
-- ============================================

CREATE OR REPLACE FUNCTION public.order_assign_card(_order_id TEXT)
RETURNS TABLE (ok BOOLEAN, message TEXT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $func$
DECLARE
  o RECORD;
  cs RECORD;
  new_timeline JSONB;
BEGIN
  SELECT * INTO o FROM public.orders WHERE id = _order_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN QUERY SELECT false, '订单不存在';
    RETURN;
  END IF;
  IF o.status = 'completed' THEN
    -- 幂等重入（如重复对账）也要跑一次加白检查：内部有存在性守卫，不会重复插入
    PERFORM public.auto_whitelist_check(_order_id);
    RETURN QUERY SELECT true, '订单已完成';
    RETURN;
  END IF;
  IF o.status NOT IN ('pending_payment', 'pay_processing', 'paid_pending_delivery') THEN
    RETURN QUERY SELECT false, '当前状态不可发货';
    RETURN;
  END IF;

  SELECT * INTO cs FROM public.card_secrets
    WHERE product_id = o.product_id AND status = 'unused' ORDER BY created_at ASC LIMIT 1 FOR UPDATE;
  IF NOT FOUND THEN
    new_timeline := o.timeline || jsonb_build_object('at', now(), 'label', '已收款，暂无卡密待补发');
    UPDATE public.orders SET status = 'paid_pending_delivery', timeline = new_timeline, updated_at = NOW()
      WHERE id = _order_id;
    -- 钱已到账只是缺货，同样计入成交并触发加白检查
    PERFORM public.auto_whitelist_check(_order_id);
    RETURN QUERY SELECT true, '已收款，但该商品暂无可用卡密，请导入后手动发货';
    RETURN;
  END IF;

  UPDATE public.card_secrets SET status = 'used', order_id = _order_id, used_at = NOW() WHERE id = cs.id;
  new_timeline := o.timeline || jsonb_build_object('at', now(), 'label', '在线支付到账') || jsonb_build_object('at', now(), 'label', '自动发货完成');
  UPDATE public.orders
    SET status = 'completed', card_secret = cs.code, payment_ref = coalesce(payment_ref, 'alipay_auto'),
        timeline = new_timeline, updated_at = NOW()
    WHERE id = _order_id;
  PERFORM public.auto_whitelist_check(_order_id);
  RETURN QUERY SELECT true, '支付成功，已自动发货';
END;
$func$;

REVOKE ALL ON FUNCTION public.order_assign_card(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.order_assign_card(TEXT) TO authenticated;

