-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.card_secrets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_categories ON public.categories FOR SELECT USING (true);
CREATE POLICY admins_write_categories ON public.categories FOR ALL USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY anon_select_products ON public.products FOR SELECT USING (true);
CREATE POLICY admins_write_products ON public.products FOR ALL USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY anon_select_contents ON public.contents FOR SELECT USING (published = true OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY admins_write_contents ON public.contents FOR ALL USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY anon_select_faqs ON public.faqs FOR SELECT USING (true);
CREATE POLICY admins_write_faqs ON public.faqs FOR ALL USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY anon_select_settings ON public.site_settings FOR SELECT USING (true);
CREATE POLICY admins_write_settings ON public.site_settings FOR ALL USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY admins_all_card_secrets ON public.card_secrets FOR ALL USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY admins_all_coupons ON public.coupons FOR ALL USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY anon_insert_orders ON public.orders FOR INSERT WITH CHECK (user_id IS NULL OR user_id = auth.uid());
CREATE POLICY users_select_own_orders ON public.orders FOR SELECT USING (user_id = auth.uid());
CREATE POLICY admins_all_orders ON public.orders FOR ALL USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE OR REPLACE FUNCTION public.order_verify_lookup(_order_id TEXT, _contact TEXT, _password TEXT)
RETURNS TABLE (ok BOOLEAN, reason TEXT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  o RECORD;
BEGIN
  SELECT * INTO o FROM public.orders WHERE id = _order_id;
  IF NOT FOUND THEN
    RETURN QUERY SELECT false, '订单号或查询密码不正确';
    RETURN;
  END IF;
  IF o.lookup_locked_until IS NOT NULL AND o.lookup_locked_until > NOW() THEN
    RETURN QUERY SELECT false, '尝试次数过多，请稍后再试';
    RETURN;
  END IF;
  IF _contact IS NOT NULL AND btrim(_contact) <> '' THEN
    IF lower(coalesce(o.contact_email, '')) <> lower(btrim(_contact))
       AND coalesce(o.contact_phone, '') <> btrim(_contact) THEN
      UPDATE public.orders SET lookup_fail_count = lookup_fail_count + 1,
        lookup_locked_until = CASE WHEN lookup_fail_count + 1 >= 5 THEN NOW() + INTERVAL '10 minutes' ELSE lookup_locked_until END
        WHERE id = _order_id;
      RETURN QUERY SELECT false, '订单号或查询密码不正确';
      RETURN;
    END IF;
  END IF;
  IF o.lookup_password_hash IS NULL OR
     coalesce(crypt(coalesce(_password, ''), o.lookup_password_hash) = o.lookup_password_hash, false) = false THEN
    UPDATE public.orders SET lookup_fail_count = lookup_fail_count + 1,
      lookup_locked_until = CASE WHEN lookup_fail_count + 1 >= 5 THEN NOW() + INTERVAL '10 minutes' ELSE lookup_locked_until END
      WHERE id = _order_id;
    RETURN QUERY SELECT false, '订单号或查询密码不正确';
    RETURN;
  END IF;
  UPDATE public.orders SET lookup_fail_count = 0, lookup_locked_until = NULL WHERE id = _order_id;
  RETURN QUERY SELECT true, NULL::TEXT;
END;
$$;

CREATE OR REPLACE FUNCTION public.order_confirm_payment(_order_id TEXT)
RETURNS TABLE (ok BOOLEAN, message TEXT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  o RECORD;
  cs RECORD;
  new_timeline JSONB;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RETURN QUERY SELECT false, '无权限执行该操作';
    RETURN;
  END IF;
  SELECT * INTO o FROM public.orders WHERE id = _order_id FOR UPDATE;
  IF NOT FOUND THEN RETURN QUERY SELECT false, '订单不存在'; RETURN; END IF;
  IF o.status NOT IN ('pending_payment', 'paid_pending_delivery') THEN
    RETURN QUERY SELECT false, '当前状态不可确认收款'; RETURN;
  END IF;
  IF o.status = 'pending_payment' THEN
    new_timeline := o.timeline || jsonb_build_object('at', now(), 'label', '已确认收款');
    UPDATE public.orders SET status = 'paid_pending_delivery', payment_ref = coalesce(payment_ref, '后台确认'),
      timeline = new_timeline, updated_at = NOW() WHERE id = _order_id;
  END IF;

  SELECT * INTO cs FROM public.card_secrets
    WHERE product_id = o.product_id AND status = 'unused' ORDER BY created_at ASC LIMIT 1 FOR UPDATE;
  IF NOT FOUND THEN
    RETURN QUERY SELECT true, '已确认收款，但该商品暂无可用卡密，请导入后手动发货';
    RETURN;
  END IF;
  UPDATE public.card_secrets SET status = 'used', order_id = _order_id, used_at = NOW() WHERE id = cs.id;
  new_timeline := (SELECT timeline FROM public.orders WHERE id = _order_id) || jsonb_build_object('at', now(), 'label', '自动发货完成');
  UPDATE public.orders SET status = 'completed', card_secret = cs.code, timeline = new_timeline, updated_at = NOW()
    WHERE id = _order_id;
  RETURN QUERY SELECT true, '已确认收款并完成自动发货';
END;
$$;

CREATE OR REPLACE FUNCTION public.order_manual_deliver(_order_id TEXT, _card_code TEXT)
RETURNS TABLE (ok BOOLEAN, message TEXT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  o RECORD;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RETURN QUERY SELECT false, '无权限执行该操作'; RETURN;
  END IF;
  SELECT * INTO o FROM public.orders WHERE id = _order_id;
  IF NOT FOUND THEN RETURN QUERY SELECT false, '订单不存在'; RETURN; END IF;
  UPDATE public.orders SET status = 'completed', card_secret = _card_code,
    timeline = timeline || jsonb_build_object('at', now(), 'label', '手动补发卡密'), updated_at = NOW()
    WHERE id = _order_id;
  RETURN QUERY SELECT true, '已完成手动发货';
END;
$$;

CREATE OR REPLACE FUNCTION public.order_close(_order_id TEXT)
RETURNS TABLE (ok BOOLEAN, message TEXT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  o RECORD;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RETURN QUERY SELECT false, '无权限执行该操作'; RETURN;
  END IF;
  SELECT * INTO o FROM public.orders WHERE id = _order_id;
  IF NOT FOUND THEN RETURN QUERY SELECT false, '订单不存在'; RETURN; END IF;
  UPDATE public.orders SET status = 'closed',
    timeline = timeline || jsonb_build_object('at', now(), 'label', '订单已关闭'), updated_at = NOW()
    WHERE id = _order_id;
  RETURN QUERY SELECT true, '订单已关闭';
END;
$$;

CREATE OR REPLACE FUNCTION public.coupon_try(_code TEXT, _amount NUMERIC, _user_id UUID)
RETURNS TABLE (ok BOOLEAN, discount NUMERIC, reason TEXT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  c RECORD;
  used_by_user INT;
BEGIN
  SELECT * INTO c FROM public.coupons WHERE upper(code) = upper(btrim(coalesce(_code, '')));
  IF NOT FOUND THEN RETURN QUERY SELECT false, 0, '优惠码不存在'; RETURN; END IF;
  IF c.is_active = false THEN RETURN QUERY SELECT false, 0, '优惠码已停用'; RETURN; END IF;
  IF c.expires_at IS NOT NULL AND c.expires_at < NOW() THEN RETURN QUERY SELECT false, 0, '优惠码已过期'; RETURN; END IF;
  IF c.used_count >= c.max_uses THEN RETURN QUERY SELECT false, 0, '优惠码已被领完'; RETURN; END IF;
  IF _amount < c.min_amount THEN RETURN QUERY SELECT false, 0, '订单金额未达到使用门槛'; RETURN; END IF;
  IF _user_id IS NOT NULL THEN
    SELECT count(*) INTO used_by_user FROM public.orders
      WHERE coupon_code = c.code AND (user_id = _user_id OR (user_id IS NULL AND _user_id IS NULL));
    IF used_by_user >= c.per_user_limit THEN RETURN QUERY SELECT false, 0, '该优惠码每人限用次数已达上限'; RETURN; END IF;
  END IF;
  IF c.type = 'percent' THEN
    RETURN QUERY SELECT true, round(_amount * c.value / 100, 2), NULL::TEXT;
  ELSE
    RETURN QUERY SELECT true, LEAST(c.value, _amount), NULL::TEXT;
  END IF;
END;
$$;

