-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- ============================================
-- 自动加白第一步：给 rate_limit_whitelist 标记来源 + 新增达标判定函数
--   · source='manual' 店主手填；source='auto' 系统按累计成交单数自动加入
--   · auto_whitelist_check(_order_id) 由发卡链路内部调用，⚠️ 不设 admin 守卫
--     （服务身份上下文 auth.uid() 恒为 NULL，加守卫会导致永远不加白）
--   · 阈值默认 1：只要成功付过一笔款就永久不再被下单次数限制挡住（用户指定）
-- ============================================

ALTER TABLE public.rate_limit_whitelist
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'manual'
  CHECK (source IN ('manual', 'auto'));

COMMENT ON COLUMN public.rate_limit_whitelist.source IS 'manual = 店主手动添加；auto = 累计付款满阈值单数由系统自动加入';

CREATE OR REPLACE FUNCTION public.auto_whitelist_check(_order_id TEXT)
RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $func$
DECLARE
  cfg JSONB;                 -- ⚠️ 必须是 JSONB：写成 RECORD 会让 ->> 抛 42883
  o RECORD;
  thr INT;
  on_flag BOOLEAN;
  e_norm TEXT;
  p_norm TEXT;
  n INT;
BEGIN
  SELECT value INTO cfg FROM public.site_settings WHERE key = 'captcha';
  on_flag := coalesce((cfg->>'auto_whitelist_enabled')::BOOLEAN, true);
  IF on_flag IS FALSE THEN RETURN NULL; END IF;          -- 关闭后不再自动加入，已有记录保持有效
  thr := coalesce((cfg->>'auto_whitelist_threshold')::INT, 1);
  IF thr < 1 THEN thr := 1; END IF;

  SELECT * INTO o FROM public.orders WHERE id = btrim(_order_id);
  IF NOT FOUND THEN RETURN '订单不存在'; END IF;
  -- 归一化口径与 order_create 频控、normalize_contact 完全一致
  e_norm := nullif(lower(btrim(coalesce(o.contact_email, ''))), '');
  p_norm := nullif(btrim(regexp_replace(coalesce(o.contact_phone, ''), '[^0-9+]', '', 'g')), '');
  IF e_norm IS NULL AND p_norm IS NULL THEN RETURN NULL; END IF;

  -- 邮箱与手机号各自独立判定并登记：频控是「任一匹配即拦」，豁免也必须「任一匹配即放」才对称
  IF e_norm IS NOT NULL THEN
    -- 店主主动移除过的联系方式不再自动加回（尊重人的决定优先于自动化）
    IF NOT EXISTS (SELECT 1 FROM public.rate_limit_whitelist w
                    WHERE w.contact_type = 'email' AND w.contact_value = e_norm) THEN
      SELECT count(*) INTO n FROM public.orders
       WHERE status IN ('paid_pending_delivery', 'completed')
         AND coalesce(is_recharge, false) IS FALSE
         AND lower(btrim(contact_email)) = e_norm;
      IF n >= thr THEN
        INSERT INTO public.rate_limit_whitelist
          (contact_type, contact_value, raw_value, note, created_by, source, is_active)
        VALUES ('email', e_norm, e_norm,
                format('累计付款满 %s 单自动加入', thr), NULL, 'auto', true);
      END IF;
    END IF;
  END IF;

  IF p_norm IS NOT NULL THEN
    IF NOT EXISTS (SELECT 1 FROM public.rate_limit_whitelist w
                    WHERE w.contact_type = 'phone' AND w.contact_value = p_norm) THEN
      SELECT count(*) INTO n FROM public.orders
       WHERE status IN ('paid_pending_delivery', 'completed')
         AND coalesce(is_recharge, false) IS FALSE
         AND btrim(regexp_replace(coalesce(contact_phone, ''), '[^0-9+]', '', 'g')) = p_norm;
      IF n >= thr THEN
        INSERT INTO public.rate_limit_whitelist
          (contact_type, contact_value, raw_value, note, created_by, source, is_active)
        VALUES ('phone', p_norm, p_norm,
                format('累计付款满 %s 单自动加入', thr), NULL, 'auto', true);
      END IF;
    END IF;
  END IF;

  RETURN NULL;
EXCEPTION WHEN unique_violation THEN
  RETURN NULL;   -- 并发重复插入：部分唯一索引兜住，视为已加白
WHEN OTHERS THEN
  RETURN '自动加白检查失败：' || SQLERRM;
END;
$func$;

REVOKE ALL ON FUNCTION public.auto_whitelist_check(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.auto_whitelist_check(TEXT) TO anon, authenticated;

