-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- ============================================
-- 频控配套两张表：白名单（跳过次数限制）+ 拦截日志（判断误伤）
-- ============================================

-- ① 频控白名单：店主测试账号 / 老顾客，命中即跳过下单次数限制
CREATE TABLE IF NOT EXISTS public.rate_limit_whitelist (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  contact_type TEXT NOT NULL CHECK (contact_type IN ('email', 'phone')),
  contact_value TEXT NOT NULL,
  raw_value TEXT,
  note TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.rate_limit_whitelist IS '下单频控白名单：按联系方式（邮箱/手机号）跳过次数限制，不影响黑名单与人机校验';
COMMENT ON COLUMN public.rate_limit_whitelist.contact_value IS '归一化后的联系方式（邮箱转小写去空格，手机号只留数字和加号）';
COMMENT ON COLUMN public.rate_limit_whitelist.is_active IS 'false 表示已移除（软删除，保留历史）';

CREATE UNIQUE INDEX IF NOT EXISTS rate_limit_whitelist_active_key
  ON public.rate_limit_whitelist (contact_type, contact_value)
  WHERE is_active;

CREATE INDEX IF NOT EXISTS rate_limit_whitelist_lookup_idx
  ON public.rate_limit_whitelist (contact_value, is_active);

ALTER TABLE public.rate_limit_whitelist ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admins_select_rate_limit_whitelist ON public.rate_limit_whitelist;
CREATE POLICY admins_select_rate_limit_whitelist ON public.rate_limit_whitelist
  FOR SELECT USING (public.has_role(auth.uid(), 'admin'));

DROP POLICY IF EXISTS admins_insert_rate_limit_whitelist ON public.rate_limit_whitelist;
CREATE POLICY admins_insert_rate_limit_whitelist ON public.rate_limit_whitelist
  FOR INSERT WITH CHECK (public.has_role(auth.uid(), 'admin'));

DROP POLICY IF EXISTS admins_update_rate_limit_whitelist ON public.rate_limit_whitelist;
CREATE POLICY admins_update_rate_limit_whitelist ON public.rate_limit_whitelist
  FOR UPDATE USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- ② 频控拦截日志：被拦请求不会 INSERT orders，必须单独记审计行
CREATE TABLE IF NOT EXISTS public.rate_limit_blocks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  contact_type TEXT NOT NULL,
  contact_value TEXT NOT NULL,
  user_id UUID,
  window_seconds INT NOT NULL,
  max_orders INT NOT NULL,
  recent_count INT NOT NULL,
  blocked_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.rate_limit_blocks IS '下单频控拦截日志：记录被拦联系方式、当时规则与实际单数，供管理员判断误伤';
COMMENT ON COLUMN public.rate_limit_blocks.recent_count IS '拦截那一刻窗口内该联系方式的既有订单数';

CREATE INDEX IF NOT EXISTS rate_limit_blocks_time_idx
  ON public.rate_limit_blocks (blocked_at DESC);

CREATE INDEX IF NOT EXISTS rate_limit_blocks_contact_idx
  ON public.rate_limit_blocks (contact_value, blocked_at DESC);

ALTER TABLE public.rate_limit_blocks ENABLE ROW LEVEL SECURITY;

-- 仅管理员可读；写入全部由 order_create（SECURITY DEFINER）内部完成，不开放任何 INSERT 策略
DROP POLICY IF EXISTS admins_select_rate_limit_blocks ON public.rate_limit_blocks;
CREATE POLICY admins_select_rate_limit_blocks ON public.rate_limit_blocks
  FOR SELECT USING (public.has_role(auth.uid(), 'admin'));

