-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 1) order_create：建单时写入 30 分钟支付时限（参数签名与返回结构完全不变）
CREATE OR REPLACE FUNCTION public.order_create(
  _id TEXT,
  _product_id TEXT,
  _product_snapshot JSONB,
  _quantity INT,
  _contact_email TEXT,
  _contact_phone TEXT,
  _lookup_password_hash TEXT,
  _note TEXT,
  _amount NUMERIC,
  _coupon_code TEXT DEFAULT NULL
)
RETURNS TABLE (ok BOOLEAN, order_id TEXT, message TEXT, discount NUMERIC)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $func$
DECLARE
  p RECORD;
  o RECORD;
  total NUMERIC(10,2);
  payable NUMERIC(10,2);
  disc NUMERIC(10,2) := 0;
  uid UUID;
BEGIN
  IF _id IS NULL OR _id !~ '^ZH\d{8}[A-Z0-9]{6}$' THEN
    RETURN QUERY SELECT false, NULL::TEXT, '订单号格式不正确', 0::NUMERIC;
    RETURN;
  END IF;
  IF _lookup_password_hash IS NULL OR length(_lookup_password_hash) <> 64 THEN
    RETURN QUERY SELECT false, NULL::TEXT, '查询密码无效', 0::NUMERIC;
    RETURN;
  END IF;
  IF (_contact_email IS NULL OR btrim(_contact_email) = '')
     AND (_contact_phone IS NULL OR btrim(_contact_phone) = '') THEN
    RETURN QUERY SELECT false, NULL::TEXT, '请至少填写邮箱或手机号', 0::NUMERIC;
    RETURN;
  END IF;

  -- 黑名单拦截（服务端强制，前端无法绕过）
  IF EXISTS (
    SELECT 1 FROM public.blocked_customers b
     WHERE b.is_active
       AND (
         (b.contact_type = 'email' AND b.contact_value = lower(btrim(coalesce(_contact_email, ''))))
         OR (b.contact_type = 'phone' AND b.contact_value = btrim(regexp_replace(coalesce(_contact_phone, ''), '[^0-9+]', '', 'g')))
       )
       AND (nullif(lower(btrim(coalesce(_contact_email, ''))), '') IS NOT NULL
            OR nullif(btrim(regexp_replace(coalesce(_contact_phone, ''), '[^0-9+]', '', 'g')), '') IS NOT NULL)
  ) THEN
    RETURN QUERY SELECT false, NULL::TEXT, '您暂时无法下单，请联系客服处理', 0::NUMERIC;
    RETURN;
  END IF;

  SELECT * INTO p FROM public.products WHERE id = _product_id AND is_active = true;
  IF NOT FOUND THEN
    RETURN QUERY SELECT false, NULL::TEXT, '商品不存在或已下架', 0::NUMERIC;
    RETURN;
  END IF;

  IF _quantity IS NULL OR _quantity < 1 OR _quantity > 10 THEN
    RETURN QUERY SELECT false, NULL::TEXT, '购买数量需在 1-10 之间', 0::NUMERIC;
    RETURN;
  END IF;
  total := round(p.price * _quantity, 2);

  uid := auth.uid();

  IF _coupon_code IS NOT NULL AND btrim(_coupon_code) <> '' THEN
    IF uid IS NULL THEN
      RETURN QUERY SELECT false, NULL::TEXT, '请先登录后再使用奖励券', 0::NUMERIC;
      RETURN;
    END IF;
    UPDATE public.referral_rewards
       SET status = 'used', used_at = NOW()
     WHERE code = upper(btrim(_coupon_code)) AND inviter_id = uid AND status = 'available'
     RETURNING * INTO o;
    IF NOT FOUND THEN
      RETURN QUERY SELECT false, NULL::TEXT, '奖励券无效或已被使用', 0::NUMERIC;
      RETURN;
    END IF;
    IF total < o.min_amount THEN
      UPDATE public.referral_rewards SET status = 'available', used_at = NULL WHERE id = o.id;
      RETURN QUERY SELECT false, NULL::TEXT, format('未满 ¥%s 无法使用该券', to_char(o.min_amount, 'FM999999990')), 0::NUMERIC;
      RETURN;
    END IF;
    disc := LEAST(o.amount, total - 1);
    IF disc < 0 THEN disc := 0; END IF;
  END IF;

  payable := round(total - disc, 2);
  IF _amount IS NULL OR abs(_amount - payable) > 0.01 THEN
    IF disc > 0 THEN
      UPDATE public.referral_rewards SET status = 'available', used_at = NULL WHERE code = upper(btrim(_coupon_code));
    END IF;
    RETURN QUERY SELECT false, NULL::TEXT, '金额校验不通过，请刷新后重试', 0::NUMERIC;
    RETURN;
  END IF;

  INSERT INTO public.orders (
    id, user_id, product_id, product_snapshot, quantity, contact_email, contact_phone,
    lookup_password_hash, note, amount, discount_amount, coupon_code, status, expires_at
  ) VALUES (
    _id, uid, _product_id, _product_snapshot, _quantity,
    nullif(btrim(coalesce(_contact_email, '')), ''),
    nullif(btrim(coalesce(_contact_phone, '')), ''),
    _lookup_password_hash,
    nullif(btrim(coalesce(_note, '')), ''),
    payable, disc,
    CASE WHEN disc > 0 THEN upper(btrim(_coupon_code)) ELSE NULL END,
    'pending_payment',
    NOW() + INTERVAL '30 minutes'
  );
  RETURN QUERY SELECT true, _id, NULL::TEXT, disc;
EXCEPTION WHEN unique_violation THEN
  IF disc > 0 THEN
    UPDATE public.referral_rewards SET status = 'available', used_at = NULL WHERE code = upper(btrim(_coupon_code));
  END IF;
  RETURN QUERY SELECT false, NULL::TEXT, '订单号重复，请重试', 0::NUMERIC;
END;
$func$;

REVOKE ALL ON FUNCTION public.order_create(TEXT, TEXT, JSONB, INT, TEXT, TEXT, TEXT, TEXT, NUMERIC, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.order_create(TEXT, TEXT, JSONB, INT, TEXT, TEXT, TEXT, TEXT, NUMERIC, TEXT) TO anon, authenticated;


-- 2) order_close：保持单参数签名（避免 PostgreSQL 重载歧义），内部固定写 admin_manual，并补齐奖励券返还
DROP FUNCTION IF EXISTS public.order_close(TEXT);

CREATE OR REPLACE FUNCTION public.order_close(_order_id TEXT)
RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $func$
DECLARE
  o RECORD;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RETURN '无权限执行该操作';
  END IF;
  SELECT * INTO o FROM public.orders WHERE id = _order_id;
  IF NOT FOUND THEN RETURN '订单不存在'; END IF;
  IF o.status = 'closed' THEN RETURN NULL; END IF; -- 幂等：已关闭视为成功
  UPDATE public.orders SET status = 'closed', close_reason = 'admin_manual',
    timeline = timeline || jsonb_build_object('at', now(), 'label', '管理员手动关闭'), updated_at = NOW()
    WHERE id = _order_id;
  -- 已抵扣的奖励券退回可用，与超时自动关单同一套返还规则
  IF o.coupon_code IS NOT NULL AND o.discount_amount > 0 THEN
    UPDATE public.referral_rewards SET status = 'available', used_at = NULL
     WHERE code = o.coupon_code AND status = 'used';
  END IF;
  RETURN NULL; -- NULL = 成功
EXCEPTION WHEN OTHERS THEN
  RETURN '关闭失败：' || SQLERRM;
END;
$func$;

REVOKE ALL ON FUNCTION public.order_close(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.order_close(TEXT) TO authenticated;


-- 3) 定时扫描函数：关闭已过支付时限、且确实没有付款记录的订单
--    pay_processing（已出码在途）的单不在这里直接关，必须等 alipay-pay expire-check
--    向支付宝确认「查无此单 / 未支付」后调用 order_expire_close 逐单关闭，避免误杀临界时刻付款。
CREATE OR REPLACE FUNCTION public.order_expire_sweep()
RETURNS INTEGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $func$
DECLARE
  n INTEGER;
BEGIN
  WITH cand AS (
    SELECT id, coupon_code, discount_amount FROM public.orders
     WHERE status = 'pending_payment'
       AND expires_at IS NOT NULL
       AND expires_at < NOW()
       AND card_secret IS NULL
     FOR UPDATE SKIP LOCKED
  ),
  closed AS (
    UPDATE public.orders o
       SET status = 'closed',
           close_reason = 'timeout_auto',
           timeline = o.timeline || jsonb_build_object('at', now(), 'label', '超时未付款，系统自动关闭'),
           updated_at = NOW()
      FROM (SELECT id FROM cand) c
     WHERE o.id = c.id
     RETURNING o.id
  ),
  refunded AS (
    UPDATE public.referral_rewards r
       SET status = 'available', used_at = NULL
      FROM cand c
     WHERE r.code = c.coupon_code AND r.status = 'used'
       AND c.discount_amount > 0 AND c.coupon_code IS NOT NULL
  )
  SELECT count(*) INTO n FROM closed;

  RETURN n;
END;
$func$;

REVOKE ALL ON FUNCTION public.order_expire_sweep() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.order_expire_sweep() TO authenticated;


-- 4) 单笔强制关闭（供核账流程在确认支付宝侧未支付后调用）
CREATE OR REPLACE FUNCTION public.order_expire_close(_order_id TEXT)
RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $func$
DECLARE
  o RECORD;
BEGIN
  SELECT * INTO o FROM public.orders WHERE id = _order_id;
  IF NOT FOUND THEN RETURN '订单不存在'; END IF;
  IF o.status = 'closed' THEN RETURN NULL; END IF; -- 幂等
  IF o.status NOT IN ('pending_payment', 'pay_processing') THEN RETURN NULL; END IF; -- 已完成/核账中不动
  IF o.card_secret IS NOT NULL THEN RETURN NULL; END IF; -- 已发卡绝不回收

  UPDATE public.orders
     SET status = 'closed', close_reason = 'timeout_auto',
         timeline = timeline || jsonb_build_object('at', now(), 'label', '超时未付款，系统自动关闭'),
         updated_at = NOW()
   WHERE id = _order_id;

  IF o.coupon_code IS NOT NULL AND o.discount_amount > 0 THEN
    UPDATE public.referral_rewards SET status = 'available', used_at = NULL
     WHERE code = o.coupon_code AND status = 'used';
  END IF;
  RETURN NULL; -- NULL = 成功
EXCEPTION WHEN OTHERS THEN
  RETURN '关闭失败：' || SQLERRM;
END;
$func$;

REVOKE ALL ON FUNCTION public.order_expire_close(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.order_expire_close(TEXT) TO authenticated;

