-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 创建商品图片存储桶（公开可读，仅管理员可写）
INSERT INTO storage.buckets (id, name, public)
VALUES (gen_random_uuid(), 'product-images', true)
ON CONFLICT (id) DO NOTHING;

-- 允许 anon/authenticated 读取该 bucket 元数据（storage.objects 策略需按 name 查 id）
CREATE POLICY clients_select_product_images_bucket ON storage.buckets
FOR SELECT TO anon, authenticated
USING (name = 'product-images');

-- 仅管理员可上传
CREATE POLICY admins_insert_product_images ON storage.objects
FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = (SELECT id FROM storage.buckets WHERE name = 'product-images')
  AND public.has_role(auth.uid(), 'admin')
);

-- 所有人可读（商品图本就公开）
CREATE POLICY public_select_product_images ON storage.objects
FOR SELECT TO anon, authenticated
USING (
  bucket_id = (SELECT id FROM storage.buckets WHERE name = 'product-images')
);

