-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

-- 黑名单管理函数（SECURITY DEFINER，内部校验 admin）
-- 返回值范式沿用本项目：标量 TEXT，NULL = 成功，非 NULL = 错误文案

CREATE OR REPLACE FUNCTION public.normalize_contact(_type TEXT, _value TEXT)
RETURNS TEXT
LANGUAGE SQL IMMUTABLE
AS $$
  SELECT CASE
    WHEN _type = 'email' THEN lower(btrim(coalesce(_value, '')))
    WHEN _type = 'phone' THEN btrim(regexp_replace(coalesce(_value, ''), '[^0-9+]', '', 'g'))
    ELSE ''
  END;
$$;

CREATE OR REPLACE FUNCTION public.customer_block(
  _contact_type TEXT,
  _contact_value TEXT,
  _reason TEXT DEFAULT '多次下单未支付'
)
RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_norm TEXT;
  v_id UUID;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RETURN '无权限执行此操作';
  END IF;
  IF _contact_type NOT IN ('email', 'phone') THEN
    RETURN '联系方式类型不合法';
  END IF;
  v_norm := public.normalize_contact(_contact_type, _contact_value);
  IF v_norm = '' THEN
    RETURN '请填写要拉黑的邮箱或手机号';
  END IF;

  -- 已有生效记录 → 视为重复
  SELECT id INTO v_id FROM blocked_customers
   WHERE contact_type = _contact_type AND contact_value = v_norm AND is_active
   LIMIT 1;
  IF v_id IS NOT NULL THEN
    RETURN '该联系方式已在黑名单中';
  END IF;

  -- 有已解除的历史记录 → 重新置为生效
  UPDATE blocked_customers
     SET is_active = true, reason = coalesce(nullif(btrim(_reason), ''), '多次下单未支付'),
         raw_value = btrim(_contact_value), created_by = auth.uid(), updated_at = now()
   WHERE contact_type = _contact_type AND contact_value = v_norm
     AND id = (SELECT id FROM blocked_customers
                WHERE contact_type = _contact_type AND contact_value = v_norm AND NOT is_active
                ORDER BY updated_at DESC LIMIT 1);
  IF FOUND THEN
    RETURN NULL;
  END IF;

  INSERT INTO blocked_customers (contact_type, contact_value, raw_value, reason, created_by)
  VALUES (_contact_type, v_norm, btrim(_contact_value),
          coalesce(nullif(btrim(_reason), ''), '多次下单未支付'), auth.uid());
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.customer_unblock(_id UUID)
RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_ok BOOLEAN;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RETURN '无权限执行此操作';
  END IF;
  UPDATE blocked_customers
     SET is_active = false, updated_at = now()
   WHERE id = _id AND is_active;
  GET DIAGNOSTICS v_ok = ROW_COUNT;
  IF v_ok IS FALSE OR v_ok IS NULL THEN
    RETURN '该记录已解除或不存在，请刷新后重试';
  END IF;
  RETURN NULL;
END;
$$;

-- 可疑买家统计：按联系方式聚合下单总数 / 已完成 / 未支付
CREATE OR REPLACE FUNCTION public.admin_suspect_buyers(_threshold INT DEFAULT 5)
RETURNS TABLE (
  contact_type TEXT,
  contact_value TEXT,
  display_value TEXT,
  total_orders BIGINT,
  paid_orders BIGINT,
  unpaid_orders BIGINT,
  last_order_at TIMESTAMPTZ
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RETURN;
  END IF;
  RETURN QUERY
  WITH grouped AS (
    SELECT
      CASE WHEN o.contact_email IS NOT NULL AND btrim(o.contact_email) <> ''
           THEN 'email' ELSE 'phone' END AS ctype,
      CASE WHEN o.contact_email IS NOT NULL AND btrim(o.contact_email) <> ''
           THEN lower(btrim(o.contact_email))
           ELSE btrim(regexp_replace(coalesce(o.contact_phone, ''), '[^0-9+]', '', 'g'))
      END AS cvalue,
      count(*) AS total,
      count(*) FILTER (WHERE o.status IN ('paid_pending_delivery', 'completed')
                        OR o.card_secret IS NOT NULL) AS paid,
      count(*) FILTER (WHERE o.status IN ('pending_payment', 'pay_processing', 'closed')
                        AND o.card_secret IS NULL) AS unpaid,
      max(o.created_at) AS last_at
    FROM orders o
    WHERE (o.contact_email IS NOT NULL AND btrim(o.contact_email) <> '')
       OR (o.contact_phone IS NOT NULL AND btrim(o.contact_phone) <> '')
    GROUP BY 1, 2
  )
  SELECT
    g.ctype,
    g.cvalue,
    g.cvalue AS display_value,
    g.total,
    g.paid,
    g.unpaid,
    g.last_at
  FROM grouped g
  WHERE g.unpaid >= greatest(coalesce(_threshold, 5), 1)
     OR g.total >= greatest(coalesce(_threshold, 5), 1)
  ORDER BY g.unpaid DESC, g.total DESC, g.last_at DESC
  LIMIT 100;
END;
$$;

REVOKE ALL ON FUNCTION public.normalize_contact(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.customer_block(TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.customer_unblock(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_suspect_buyers(INT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.customer_block(TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.customer_unblock(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_suspect_buyers(INT) TO authenticated;

