-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE public.categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.products (
  id TEXT PRIMARY KEY,
  category_slug TEXT REFERENCES public.categories(slug) ON DELETE SET NULL,
  badge TEXT,
  title TEXT NOT NULL,
  subtitle TEXT,
  price NUMERIC(10,2) NOT NULL,
  original_price NUMERIC(10,2),
  cover_url TEXT,
  delivery_method TEXT DEFAULT 'auto',
  stock_level TEXT DEFAULT 'many',
  sold_base INT DEFAULT 0,
  tips_title TEXT DEFAULT '商品详情',
  tips_body TEXT,
  risk_title TEXT DEFAULT '使用提醒',
  risk_body TEXT,
  official_title TEXT DEFAULT '风险说明',
  official_body TEXT,
  support_title TEXT DEFAULT '常见问题',
  support_body TEXT,
  faq JSONB DEFAULT '[]'::jsonb,
  payment_methods JSONB DEFAULT '["alipay","usdt"]'::jsonb,
  is_active BOOLEAN DEFAULT true,
  is_hot BOOLEAN DEFAULT false,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.card_secrets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id TEXT REFERENCES public.products(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  note TEXT,
  status TEXT DEFAULT 'unused',
  order_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  used_at TIMESTAMPTZ
);

CREATE TABLE public.orders (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  product_id TEXT,
  product_snapshot JSONB NOT NULL,
  quantity INT DEFAULT 1,
  contact_email TEXT,
  contact_phone TEXT,
  lookup_password_hash TEXT,
  lookup_fail_count INT DEFAULT 0,
  lookup_locked_until TIMESTAMPTZ,
  note TEXT,
  payment_method TEXT,
  payment_ref TEXT,
  amount NUMERIC(10,2) NOT NULL,
  discount_amount NUMERIC(10,2) DEFAULT 0,
  coupon_code TEXT,
  status TEXT DEFAULT 'pending_payment',
  card_secret TEXT,
  timeline JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.coupons (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT UNIQUE NOT NULL,
  type TEXT DEFAULT 'fixed',
  value NUMERIC(10,2) NOT NULL,
  min_amount NUMERIC(10,2) DEFAULT 0,
  max_uses INT DEFAULT 100,
  used_count INT DEFAULT 0,
  per_user_limit INT DEFAULT 1,
  expires_at TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.contents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  kind TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  summary TEXT,
  body TEXT,
  cover_url TEXT,
  tags JSONB DEFAULT '[]'::jsonb,
  related_products JSONB DEFAULT '[]'::jsonb,
  published BOOLEAN DEFAULT true,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.faqs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  group_name TEXT DEFAULT '通用',
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.site_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

