// ============================================
// 此文件由 Meoo Cloud 自动生成，请勿修改
// This file is auto-generated by Meoo Cloud, DO NOT MODIFY
// ============================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      blocked_customers: {
        Row: {
          contact_type: string
          contact_value: string
          created_at: string
          created_by: string | null
          id: string
          is_active: boolean
          raw_value: string | null
          reason: string | null
          updated_at: string
        }
        Insert: {
          contact_type: string
          contact_value: string
          created_at?: string
          created_by?: string | null
          id?: string
          is_active?: boolean
          raw_value?: string | null
          reason?: string | null
          updated_at?: string
        }
        Update: {
          contact_type?: string
          contact_value?: string
          created_at?: string
          created_by?: string | null
          id?: string
          is_active?: boolean
          raw_value?: string | null
          reason?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      card_secrets: {
        Row: {
          code: string
          created_at: string | null
          id: string
          note: string | null
          order_id: string | null
          product_id: string | null
          status: string | null
          used_at: string | null
        }
        Insert: {
          code: string
          created_at?: string | null
          id?: string
          note?: string | null
          order_id?: string | null
          product_id?: string | null
          status?: string | null
          used_at?: string | null
        }
        Update: {
          code?: string
          created_at?: string | null
          id?: string
          note?: string | null
          order_id?: string | null
          product_id?: string | null
          status?: string | null
          used_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "card_secrets_product_id_fkey"
            columns: ["product_id"]
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      categories: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          name: string
          slug: string
          sort_order: number | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          name: string
          slug: string
          sort_order?: number | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          name?: string
          slug?: string
          sort_order?: number | null
        }
        Relationships: []
      }
      commission_records: {
        Row: {
          base_amount: number
          coupon_id: string | null
          created_at: string
          id: string
          invitee_id: string | null
          inviter_id: string
          order_id: string
          product_id: string | null
          product_title: string | null
          reward_amount: number
          status: string
        }
        Insert: {
          base_amount?: number
          coupon_id?: string | null
          created_at?: string
          id?: string
          invitee_id?: string | null
          inviter_id: string
          order_id: string
          product_id?: string | null
          product_title?: string | null
          reward_amount?: number
          status?: string
        }
        Update: {
          base_amount?: number
          coupon_id?: string | null
          created_at?: string
          id?: string
          invitee_id?: string | null
          inviter_id?: string
          order_id?: string
          product_id?: string | null
          product_title?: string | null
          reward_amount?: number
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "commission_records_coupon_id_fkey"
            columns: ["coupon_id"]
            referencedRelation: "referral_rewards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "commission_records_invitee_id_fkey"
            columns: ["invitee_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "commission_records_inviter_id_fkey"
            columns: ["inviter_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "commission_records_order_id_fkey"
            columns: ["order_id"]
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      contents: {
        Row: {
          body: string | null
          cover_url: string | null
          created_at: string | null
          id: string
          kind: string
          published: boolean | null
          related_products: Json | null
          slug: string
          sort_order: number | null
          summary: string | null
          tags: Json | null
          title: string
          updated_at: string | null
        }
        Insert: {
          body?: string | null
          cover_url?: string | null
          created_at?: string | null
          id?: string
          kind: string
          published?: boolean | null
          related_products?: Json | null
          slug: string
          sort_order?: number | null
          summary?: string | null
          tags?: Json | null
          title: string
          updated_at?: string | null
        }
        Update: {
          body?: string | null
          cover_url?: string | null
          created_at?: string | null
          id?: string
          kind?: string
          published?: boolean | null
          related_products?: Json | null
          slug?: string
          sort_order?: number | null
          summary?: string | null
          tags?: Json | null
          title?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      coupons: {
        Row: {
          code: string
          created_at: string | null
          expires_at: string | null
          id: string
          is_active: boolean | null
          max_uses: number | null
          min_amount: number | null
          per_user_limit: number | null
          type: string | null
          used_count: number | null
          value: number
        }
        Insert: {
          code: string
          created_at?: string | null
          expires_at?: string | null
          id?: string
          is_active?: boolean | null
          max_uses?: number | null
          min_amount?: number | null
          per_user_limit?: number | null
          type?: string | null
          used_count?: number | null
          value: number
        }
        Update: {
          code?: string
          created_at?: string | null
          expires_at?: string | null
          id?: string
          is_active?: boolean | null
          max_uses?: number | null
          min_amount?: number | null
          per_user_limit?: number | null
          type?: string | null
          used_count?: number | null
          value?: number
        }
        Relationships: []
      }
      daily_login_users: {
        Row: {
          day: string
          user_id: string
        }
        Insert: {
          day: string
          user_id: string
        }
        Update: {
          day?: string
          user_id?: string
        }
        Relationships: []
      }
      daily_stats: {
        Row: {
          day: string
          login_users: number
          order_count: number
          revenue: number
          updated_at: string
          visits: number
        }
        Insert: {
          day: string
          login_users?: number
          order_count?: number
          revenue?: number
          updated_at?: string
          visits?: number
        }
        Update: {
          day?: string
          login_users?: number
          order_count?: number
          revenue?: number
          updated_at?: string
          visits?: number
        }
        Relationships: []
      }
      daily_visitors: {
        Row: {
          day: string
          visitor_id: string
        }
        Insert: {
          day: string
          visitor_id: string
        }
        Update: {
          day?: string
          visitor_id?: string
        }
        Relationships: []
      }
      faqs: {
        Row: {
          answer: string
          created_at: string | null
          group_name: string | null
          id: string
          question: string
          sort_order: number | null
        }
        Insert: {
          answer: string
          created_at?: string | null
          group_name?: string | null
          id?: string
          question: string
          sort_order?: number | null
        }
        Update: {
          answer?: string
          created_at?: string | null
          group_name?: string | null
          id?: string
          question?: string
          sort_order?: number | null
        }
        Relationships: []
      }
      order_captcha_challenges: {
        Row: {
          answer_hash: string
          created_at: string
          expires_at: string
          id: string
          used_at: string | null
        }
        Insert: {
          answer_hash: string
          created_at?: string
          expires_at: string
          id: string
          used_at?: string | null
        }
        Update: {
          answer_hash?: string
          created_at?: string
          expires_at?: string
          id?: string
          used_at?: string | null
        }
        Relationships: []
      }
      orders: {
        Row: {
          amount: number
          card_secret: string | null
          channel_fee: number
          close_reason: string | null
          contact_email: string | null
          contact_phone: string | null
          coupon_code: string | null
          created_at: string | null
          discount_amount: number | null
          expires_at: string | null
          goods_amount: number | null
          id: string
          is_recharge: boolean
          lookup_fail_count: number | null
          lookup_locked_until: string | null
          lookup_password_hash: string | null
          note: string | null
          payment_method: string | null
          payment_ref: string | null
          product_id: string | null
          product_snapshot: Json
          quantity: number | null
          status: string | null
          timeline: Json | null
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          amount: number
          card_secret?: string | null
          channel_fee?: number
          close_reason?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          coupon_code?: string | null
          created_at?: string | null
          discount_amount?: number | null
          expires_at?: string | null
          goods_amount?: number | null
          id: string
          is_recharge?: boolean
          lookup_fail_count?: number | null
          lookup_locked_until?: string | null
          lookup_password_hash?: string | null
          note?: string | null
          payment_method?: string | null
          payment_ref?: string | null
          product_id?: string | null
          product_snapshot: Json
          quantity?: number | null
          status?: string | null
          timeline?: Json | null
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          amount?: number
          card_secret?: string | null
          channel_fee?: number
          close_reason?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          coupon_code?: string | null
          created_at?: string | null
          discount_amount?: number | null
          expires_at?: string | null
          goods_amount?: number | null
          id?: string
          is_recharge?: boolean
          lookup_fail_count?: number | null
          lookup_locked_until?: string | null
          lookup_password_hash?: string | null
          note?: string | null
          payment_method?: string | null
          payment_ref?: string | null
          product_id?: string | null
          product_snapshot?: Json
          quantity?: number | null
          status?: string | null
          timeline?: Json | null
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "orders_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          badge: string | null
          category_slug: string | null
          commission: Json | null
          cover_url: string | null
          created_at: string | null
          delivery_method: string | null
          faq: Json | null
          id: string
          is_active: boolean | null
          is_hot: boolean | null
          official_body: string | null
          official_title: string | null
          original_price: number | null
          payment_methods: Json | null
          price: number
          redeem_url: string | null
          risk_body: string | null
          risk_title: string | null
          sold_base: number | null
          sort_order: number | null
          stock_level: string | null
          subtitle: string | null
          support_body: string | null
          support_title: string | null
          tips_body: string | null
          tips_title: string | null
          title: string
          updated_at: string | null
        }
        Insert: {
          badge?: string | null
          category_slug?: string | null
          commission?: Json | null
          cover_url?: string | null
          created_at?: string | null
          delivery_method?: string | null
          faq?: Json | null
          id: string
          is_active?: boolean | null
          is_hot?: boolean | null
          official_body?: string | null
          official_title?: string | null
          original_price?: number | null
          payment_methods?: Json | null
          price: number
          redeem_url?: string | null
          risk_body?: string | null
          risk_title?: string | null
          sold_base?: number | null
          sort_order?: number | null
          stock_level?: string | null
          subtitle?: string | null
          support_body?: string | null
          support_title?: string | null
          tips_body?: string | null
          tips_title?: string | null
          title: string
          updated_at?: string | null
        }
        Update: {
          badge?: string | null
          category_slug?: string | null
          commission?: Json | null
          cover_url?: string | null
          created_at?: string | null
          delivery_method?: string | null
          faq?: Json | null
          id?: string
          is_active?: boolean | null
          is_hot?: boolean | null
          official_body?: string | null
          official_title?: string | null
          original_price?: number | null
          payment_methods?: Json | null
          price?: number
          redeem_url?: string | null
          risk_body?: string | null
          risk_title?: string | null
          sold_base?: number | null
          sort_order?: number | null
          stock_level?: string | null
          subtitle?: string | null
          support_body?: string | null
          support_title?: string | null
          tips_body?: string | null
          tips_title?: string | null
          title?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "products_category_slug_fkey"
            columns: ["category_slug"]
            referencedRelation: "categories"
            referencedColumns: ["slug"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          contact_email: string | null
          contact_phone: string | null
          created_at: string | null
          email: string | null
          id: string
          invite_code: string | null
          invited_by: string | null
          username: string
        }
        Insert: {
          avatar_url?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          created_at?: string | null
          email?: string | null
          id: string
          invite_code?: string | null
          invited_by?: string | null
          username: string
        }
        Update: {
          avatar_url?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          created_at?: string | null
          email?: string | null
          id?: string
          invite_code?: string | null
          invited_by?: string | null
          username?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_invited_by_fkey"
            columns: ["invited_by"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      rate_limit_blocks: {
        Row: {
          blocked_at: string
          contact_type: string
          contact_value: string
          id: string
          max_orders: number
          recent_count: number
          user_id: string | null
          window_seconds: number
        }
        Insert: {
          blocked_at?: string
          contact_type: string
          contact_value: string
          id?: string
          max_orders: number
          recent_count: number
          user_id?: string | null
          window_seconds: number
        }
        Update: {
          blocked_at?: string
          contact_type?: string
          contact_value?: string
          id?: string
          max_orders?: number
          recent_count?: number
          user_id?: string | null
          window_seconds?: number
        }
        Relationships: []
      }
      rate_limit_whitelist: {
        Row: {
          contact_type: string
          contact_value: string
          created_at: string
          created_by: string | null
          id: string
          is_active: boolean
          note: string | null
          raw_value: string | null
          source: string
          updated_at: string
        }
        Insert: {
          contact_type: string
          contact_value: string
          created_at?: string
          created_by?: string | null
          id?: string
          is_active?: boolean
          note?: string | null
          raw_value?: string | null
          source?: string
          updated_at?: string
        }
        Update: {
          contact_type?: string
          contact_value?: string
          created_at?: string
          created_by?: string | null
          id?: string
          is_active?: boolean
          note?: string | null
          raw_value?: string | null
          source?: string
          updated_at?: string
        }
        Relationships: []
      }
      referral_rewards: {
        Row: {
          amount: number
          code: string
          created_at: string | null
          id: string
          invitee_id: string | null
          inviter_id: string
          min_amount: number
          status: string
          used_at: string | null
        }
        Insert: {
          amount: number
          code: string
          created_at?: string | null
          id?: string
          invitee_id?: string | null
          inviter_id: string
          min_amount?: number
          status?: string
          used_at?: string | null
        }
        Update: {
          amount?: number
          code?: string
          created_at?: string | null
          id?: string
          invitee_id?: string | null
          inviter_id?: string
          min_amount?: number
          status?: string
          used_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "referral_rewards_invitee_id_fkey"
            columns: ["invitee_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "referral_rewards_inviter_id_fkey"
            columns: ["inviter_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      site_settings: {
        Row: {
          key: string
          updated_at: string | null
          value: Json
        }
        Insert: {
          key: string
          updated_at?: string | null
          value: Json
        }
        Update: {
          key?: string
          updated_at?: string | null
          value?: Json
        }
        Relationships: []
      }
      user_roles: {
        Row: {
          id: string
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Insert: {
          id?: string
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Update: {
          id?: string
          role?: Database["public"]["Enums"]["app_role"]
          user_id?: string
        }
        Relationships: []
      }
      user_wallets: {
        Row: {
          available_balance: number
          created_at: string
          frozen_amount: number
          id: string
          total_recharged: number
          total_spent: number
          updated_at: string
          user_id: string
        }
        Insert: {
          available_balance?: number
          created_at?: string
          frozen_amount?: number
          id?: string
          total_recharged?: number
          total_spent?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          available_balance?: number
          created_at?: string
          frozen_amount?: number
          id?: string
          total_recharged?: number
          total_spent?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      wallet_transactions: {
        Row: {
          amount: number
          balance_after: number
          created_at: string
          id: string
          kind: string
          note: string | null
          order_id: string | null
          ref: string | null
          user_id: string
        }
        Insert: {
          amount: number
          balance_after: number
          created_at?: string
          id?: string
          kind: string
          note?: string | null
          order_id?: string | null
          ref?: string | null
          user_id: string
        }
        Update: {
          amount?: number
          balance_after?: number
          created_at?: string
          id?: string
          kind?: string
          note?: string | null
          order_id?: string | null
          ref?: string | null
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      admin_dashboard: {
        Args: { _days?: number }
        Returns: Json
      }
      admin_suspect_buyers: {
        Args: { _threshold?: number }
        Returns: {
          contact_type: string
          contact_value: string
          display_value: string
          total_orders: number
          paid_orders: number
          unpaid_orders: number
          last_order_at: string
        }[]
      }
      alipay_mark_settled: {
        Args: { _order_id: string; _trade_no: string }
        Returns: string
      }
      alipay_sweep_candidates: {
        Args: { _limit?: number }
        Returns: Json
      }
      alipay_sweep_pick: {
        Args: { _limit?: number }
        Returns: Json
      }
      alipay_sweep_run: {
        Args: { _limit?: number; _secret?: string }
        Returns: Json
      }
      auto_whitelist_check: {
        Args: { _order_id: string }
        Returns: string
      }
      coupon_try: {
        Args: { _code: string; _amount: number; _user_id: string }
        Returns: {
          ok: boolean
          discount: number
          reason: string
        }[]
      }
      customer_block: {
        Args: {
          _contact_type: string
          _contact_value: string
          _reason?: string
        }
        Returns: string
      }
      customer_unblock: {
        Args: { _id: string }
        Returns: string
      }
      digest_hex: {
        Args: { _text: string }
        Returns: string
      }
      has_role: {
        Args: {
          _user_id: string
          _role: Database["public"]["Enums"]["app_role"]
        }
        Returns: boolean
      }
      my_commission_records: {
        Args: Record<PropertyKey, never>
        Returns: {
          ok: boolean
          id: string
          order_id: string
          friend_name: string
          product_title: string
          base_amount: number
          reward_amount: number
          status: string
          created_at: string
        }[]
      }
      my_invite_code: {
        Args: Record<PropertyKey, never>
        Returns: {
          ok: boolean
          code: string
          message: string
        }[]
      }
      my_referral_stats: {
        Args: Record<PropertyKey, never>
        Returns: {
          ok: boolean
          invite_count: number
          available_count: number
          available_amount: number
          used_count: number
          total_commission: number
          commission_count: number
        }[]
      }
      my_wallet: {
        Args: Record<PropertyKey, never>
        Returns: Json
      }
      normalize_contact: {
        Args: { _type: string; _value: string }
        Returns: string
      }
      order_assign_card: {
        Args: { _order_id: string }
        Returns: {
          ok: boolean
          message: string
        }[]
      }
      order_captcha_purge: {
        Args: Record<PropertyKey, never>
        Returns: number
      }
      order_close: {
        Args: { _order_id: string }
        Returns: string
      }
      order_confirm_payment: {
        Args: { _order_id: string }
        Returns: {
          ok: boolean
          message: string
        }[]
      }
      order_create: {
        Args: {
          _id: string
          _product_id: string
          _product_snapshot: Json
          _quantity: number
          _contact_email: string
          _contact_phone: string
          _lookup_password_hash: string
          _note: string
          _amount: number
          _coupon_code?: string
          _challenge_id?: string
          _challenge_answer?: string
          _payment_method?: string
          _is_recharge?: boolean
        }
        Returns: {
          ok: boolean
          order_id: string
          message: string
          discount: number
          fee: number
        }[]
      }
      order_customer_cancel: {
        Args: { _order_id: string }
        Returns: string
      }
      order_expire_close: {
        Args: { _order_id: string }
        Returns: string
      }
      order_expire_sweep: {
        Args: Record<PropertyKey, never>
        Returns: number
      }
      order_manual_deliver: {
        Args: { _order_id: string; _card_code: string }
        Returns: {
          ok: boolean
          message: string
        }[]
      }
      order_mark_paid: {
        Args: { _order_id: string; _trade_no: string }
        Returns: {
          ok: boolean
          message: string
        }[]
      }
      order_pay_with_balance: {
        Args: { _order_id: string }
        Returns: string
      }
      order_set_payment_method: {
        Args: {
          _order_id: string
          _method: string
          _lookup_password_hash?: string
        }
        Returns: string
      }
      order_verify_lookup: {
        Args: { _order_id: string; _contact: string; _password: string }
        Returns: {
          ok: boolean
          reason: string
        }[]
      }
      process_order_commission: {
        Args: { _order_id: string }
        Returns: undefined
      }
      rate_limit_whitelist_add: {
        Args: { _contact_type: string; _contact_value: string; _note?: string }
        Returns: string
      }
      rate_limit_whitelist_remove: {
        Args: { _id: string }
        Returns: string
      }
      referral_bind: {
        Args: { _invite_code: string }
        Returns: {
          ok: boolean
          reward_amount: number
          message: string
        }[]
      }
      stat_track_visit: {
        Args: { _visitor_id: string }
        Returns: undefined
      }
      wallet_credit_recharge: {
        Args: { _order_id: string; _amount: number; _trade_no: string }
        Returns: string
      }
      wallet_for_update: {
        Args: { _uid: string }
        Returns: number
      }
      wallet_refund_order: {
        Args: { _order_id: string }
        Returns: string
      }
      wallet_unfreeze_pending: {
        Args: { _order_id: string }
        Returns: string
      }
    }
    Enums: {
      app_role: "admin" | "user"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof Database },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof Database }
  ? Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      app_role: ["admin", "user"],
    },
  },
} as const
