/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BossRouteImport } from './routes/boss'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutAccountRouteImport } from './routes/_layout.account'
import { Route as LayoutBlogRouteImport } from './routes/_layout.blog'
import { Route as LayoutFaqRouteImport } from './routes/_layout.faq'
import { Route as LayoutGuidesRouteImport } from './routes/_layout.guides'
import { Route as LayoutLoginRouteImport } from './routes/_layout.login'
import { Route as LayoutPoliciesRouteImport } from './routes/_layout.policies'
import { Route as LayoutRegisterRouteImport } from './routes/_layout.register'
import { Route as LayoutResetPasswordRouteImport } from './routes/_layout.reset-password'
import { Route as LayoutTutorialsRouteImport } from './routes/_layout.tutorials'
import { Route as LayoutCategorySlugRouteImport } from './routes/_layout.category.$slug'
import { Route as LayoutCheckoutIdRouteImport } from './routes/_layout.checkout.$id'
import { Route as LayoutContentSlugRouteImport } from './routes/_layout.content.$slug'
import { Route as LayoutOrdersLookupRouteImport } from './routes/_layout.orders.lookup'
import { Route as LayoutPayAlipayManualRouteImport } from './routes/_layout.pay.alipay-manual'
import { Route as LayoutPayAlipayQrRouteImport } from './routes/_layout.pay.alipay-qr'
import { Route as LayoutPayReturnRouteImport } from './routes/_layout.pay.return'
import { Route as LayoutPayWechatRouteImport } from './routes/_layout.pay.wechat'
import { Route as LayoutProductIdRouteImport } from './routes/_layout.product.$id'
import { Route as LayoutPayResumeIdRouteImport } from './routes/_layout.pay.resume_.$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BossRoute = BossRouteImport.update({
  id: '/boss',
  path: '/boss',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountRoute = LayoutAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlogRoute = LayoutBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFaqRoute = LayoutFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGuidesRoute = LayoutGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPoliciesRoute = LayoutPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRegisterRoute = LayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResetPasswordRoute = LayoutResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTutorialsRoute = LayoutTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategorySlugRoute = LayoutCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCheckoutIdRoute = LayoutCheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContentSlugRoute = LayoutContentSlugRouteImport.update({
  id: '/content/$slug',
  path: '/content/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersLookupRoute = LayoutOrdersLookupRouteImport.update({
  id: '/orders/lookup',
  path: '/orders/lookup',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPayAlipayManualRoute = LayoutPayAlipayManualRouteImport.update({
  id: '/pay/alipay-manual',
  path: '/pay/alipay-manual',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPayAlipayQrRoute = LayoutPayAlipayQrRouteImport.update({
  id: '/pay/alipay-qr',
  path: '/pay/alipay-qr',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPayReturnRoute = LayoutPayReturnRouteImport.update({
  id: '/pay/return',
  path: '/pay/return',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPayWechatRoute = LayoutPayWechatRouteImport.update({
  id: '/pay/wechat',
  path: '/pay/wechat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductIdRoute = LayoutProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPayResumeIdRoute = LayoutPayResumeIdRouteImport.update({
  id: '/pay/resume_/$id',
  path: '/pay/resume/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/admin': typeof AdminRoute
  '/boss': typeof BossRoute
  '/account': typeof LayoutAccountRoute
  '/blog': typeof LayoutBlogRoute
  '/faq': typeof LayoutFaqRoute
  '/guides': typeof LayoutGuidesRoute
  '/login': typeof LayoutLoginRoute
  '/policies': typeof LayoutPoliciesRoute
  '/register': typeof LayoutRegisterRoute
  '/reset-password': typeof LayoutResetPasswordRoute
  '/tutorials': typeof LayoutTutorialsRoute
  '/category/$slug': typeof LayoutCategorySlugRoute
  '/checkout/$id': typeof LayoutCheckoutIdRoute
  '/content/$slug': typeof LayoutContentSlugRoute
  '/orders/lookup': typeof LayoutOrdersLookupRoute
  '/pay/alipay-manual': typeof LayoutPayAlipayManualRoute
  '/pay/alipay-qr': typeof LayoutPayAlipayQrRoute
  '/pay/return': typeof LayoutPayReturnRoute
  '/pay/wechat': typeof LayoutPayWechatRoute
  '/product/$id': typeof LayoutProductIdRoute
  '/pay/resume/$id': typeof LayoutPayResumeIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/boss': typeof BossRoute
  '/account': typeof LayoutAccountRoute
  '/blog': typeof LayoutBlogRoute
  '/faq': typeof LayoutFaqRoute
  '/guides': typeof LayoutGuidesRoute
  '/login': typeof LayoutLoginRoute
  '/policies': typeof LayoutPoliciesRoute
  '/register': typeof LayoutRegisterRoute
  '/reset-password': typeof LayoutResetPasswordRoute
  '/tutorials': typeof LayoutTutorialsRoute
  '/': typeof LayoutIndexRoute
  '/category/$slug': typeof LayoutCategorySlugRoute
  '/checkout/$id': typeof LayoutCheckoutIdRoute
  '/content/$slug': typeof LayoutContentSlugRoute
  '/orders/lookup': typeof LayoutOrdersLookupRoute
  '/pay/alipay-manual': typeof LayoutPayAlipayManualRoute
  '/pay/alipay-qr': typeof LayoutPayAlipayQrRoute
  '/pay/return': typeof LayoutPayReturnRoute
  '/pay/wechat': typeof LayoutPayWechatRoute
  '/product/$id': typeof LayoutProductIdRoute
  '/pay/resume/$id': typeof LayoutPayResumeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/admin': typeof AdminRoute
  '/boss': typeof BossRoute
  '/_layout/account': typeof LayoutAccountRoute
  '/_layout/blog': typeof LayoutBlogRoute
  '/_layout/faq': typeof LayoutFaqRoute
  '/_layout/guides': typeof LayoutGuidesRoute
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/policies': typeof LayoutPoliciesRoute
  '/_layout/register': typeof LayoutRegisterRoute
  '/_layout/reset-password': typeof LayoutResetPasswordRoute
  '/_layout/tutorials': typeof LayoutTutorialsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/category/$slug': typeof LayoutCategorySlugRoute
  '/_layout/checkout/$id': typeof LayoutCheckoutIdRoute
  '/_layout/content/$slug': typeof LayoutContentSlugRoute
  '/_layout/orders/lookup': typeof LayoutOrdersLookupRoute
  '/_layout/pay/alipay-manual': typeof LayoutPayAlipayManualRoute
  '/_layout/pay/alipay-qr': typeof LayoutPayAlipayQrRoute
  '/_layout/pay/return': typeof LayoutPayReturnRoute
  '/_layout/pay/wechat': typeof LayoutPayWechatRoute
  '/_layout/product/$id': typeof LayoutProductIdRoute
  '/_layout/pay/resume_/$id': typeof LayoutPayResumeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/boss'
    | '/account'
    | '/blog'
    | '/faq'
    | '/guides'
    | '/login'
    | '/policies'
    | '/register'
    | '/reset-password'
    | '/tutorials'
    | '/category/$slug'
    | '/checkout/$id'
    | '/content/$slug'
    | '/orders/lookup'
    | '/pay/alipay-manual'
    | '/pay/alipay-qr'
    | '/pay/return'
    | '/pay/wechat'
    | '/product/$id'
    | '/pay/resume/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/boss'
    | '/account'
    | '/blog'
    | '/faq'
    | '/guides'
    | '/login'
    | '/policies'
    | '/register'
    | '/reset-password'
    | '/tutorials'
    | '/'
    | '/category/$slug'
    | '/checkout/$id'
    | '/content/$slug'
    | '/orders/lookup'
    | '/pay/alipay-manual'
    | '/pay/alipay-qr'
    | '/pay/return'
    | '/pay/wechat'
    | '/product/$id'
    | '/pay/resume/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/admin'
    | '/boss'
    | '/_layout/account'
    | '/_layout/blog'
    | '/_layout/faq'
    | '/_layout/guides'
    | '/_layout/login'
    | '/_layout/policies'
    | '/_layout/register'
    | '/_layout/reset-password'
    | '/_layout/tutorials'
    | '/_layout/'
    | '/_layout/category/$slug'
    | '/_layout/checkout/$id'
    | '/_layout/content/$slug'
    | '/_layout/orders/lookup'
    | '/_layout/pay/alipay-manual'
    | '/_layout/pay/alipay-qr'
    | '/_layout/pay/return'
    | '/_layout/pay/wechat'
    | '/_layout/product/$id'
    | '/_layout/pay/resume_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AdminRoute: typeof AdminRoute
  BossRoute: typeof BossRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boss': {
      id: '/boss'
      path: '/boss'
      fullPath: '/boss'
      preLoaderRoute: typeof BossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account': {
      id: '/_layout/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof LayoutAccountRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blog': {
      id: '/_layout/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof LayoutBlogRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/faq': {
      id: '/_layout/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof LayoutFaqRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/guides': {
      id: '/_layout/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof LayoutGuidesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/policies': {
      id: '/_layout/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof LayoutPoliciesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/register': {
      id: '/_layout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof LayoutRegisterRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reset-password': {
      id: '/_layout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof LayoutResetPasswordRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tutorials': {
      id: '/_layout/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof LayoutTutorialsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/category/$slug': {
      id: '/_layout/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof LayoutCategorySlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/checkout/$id': {
      id: '/_layout/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof LayoutCheckoutIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/content/$slug': {
      id: '/_layout/content/$slug'
      path: '/content/$slug'
      fullPath: '/content/$slug'
      preLoaderRoute: typeof LayoutContentSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders/lookup': {
      id: '/_layout/orders/lookup'
      path: '/orders/lookup'
      fullPath: '/orders/lookup'
      preLoaderRoute: typeof LayoutOrdersLookupRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pay/alipay-manual': {
      id: '/_layout/pay/alipay-manual'
      path: '/pay/alipay-manual'
      fullPath: '/pay/alipay-manual'
      preLoaderRoute: typeof LayoutPayAlipayManualRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pay/alipay-qr': {
      id: '/_layout/pay/alipay-qr'
      path: '/pay/alipay-qr'
      fullPath: '/pay/alipay-qr'
      preLoaderRoute: typeof LayoutPayAlipayQrRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pay/return': {
      id: '/_layout/pay/return'
      path: '/pay/return'
      fullPath: '/pay/return'
      preLoaderRoute: typeof LayoutPayReturnRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pay/wechat': {
      id: '/_layout/pay/wechat'
      path: '/pay/wechat'
      fullPath: '/pay/wechat'
      preLoaderRoute: typeof LayoutPayWechatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/product/$id': {
      id: '/_layout/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof LayoutProductIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pay/resume_/$id': {
      id: '/_layout/pay/resume_/$id'
      path: '/pay/resume/$id'
      fullPath: '/pay/resume/$id'
      preLoaderRoute: typeof LayoutPayResumeIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAccountRoute: typeof LayoutAccountRoute
  LayoutBlogRoute: typeof LayoutBlogRoute
  LayoutFaqRoute: typeof LayoutFaqRoute
  LayoutGuidesRoute: typeof LayoutGuidesRoute
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutPoliciesRoute: typeof LayoutPoliciesRoute
  LayoutRegisterRoute: typeof LayoutRegisterRoute
  LayoutResetPasswordRoute: typeof LayoutResetPasswordRoute
  LayoutTutorialsRoute: typeof LayoutTutorialsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCategorySlugRoute: typeof LayoutCategorySlugRoute
  LayoutCheckoutIdRoute: typeof LayoutCheckoutIdRoute
  LayoutContentSlugRoute: typeof LayoutContentSlugRoute
  LayoutOrdersLookupRoute: typeof LayoutOrdersLookupRoute
  LayoutPayAlipayManualRoute: typeof LayoutPayAlipayManualRoute
  LayoutPayAlipayQrRoute: typeof LayoutPayAlipayQrRoute
  LayoutPayReturnRoute: typeof LayoutPayReturnRoute
  LayoutPayWechatRoute: typeof LayoutPayWechatRoute
  LayoutProductIdRoute: typeof LayoutProductIdRoute
  LayoutPayResumeIdRoute: typeof LayoutPayResumeIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAccountRoute: LayoutAccountRoute,
  LayoutBlogRoute: LayoutBlogRoute,
  LayoutFaqRoute: LayoutFaqRoute,
  LayoutGuidesRoute: LayoutGuidesRoute,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutPoliciesRoute: LayoutPoliciesRoute,
  LayoutRegisterRoute: LayoutRegisterRoute,
  LayoutResetPasswordRoute: LayoutResetPasswordRoute,
  LayoutTutorialsRoute: LayoutTutorialsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCategorySlugRoute: LayoutCategorySlugRoute,
  LayoutCheckoutIdRoute: LayoutCheckoutIdRoute,
  LayoutContentSlugRoute: LayoutContentSlugRoute,
  LayoutOrdersLookupRoute: LayoutOrdersLookupRoute,
  LayoutPayAlipayManualRoute: LayoutPayAlipayManualRoute,
  LayoutPayAlipayQrRoute: LayoutPayAlipayQrRoute,
  LayoutPayReturnRoute: LayoutPayReturnRoute,
  LayoutPayWechatRoute: LayoutPayWechatRoute,
  LayoutProductIdRoute: LayoutProductIdRoute,
  LayoutPayResumeIdRoute: LayoutPayResumeIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AdminRoute: AdminRoute,
  BossRoute: BossRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
